# Generated by Django 6.0 on 2025-12-31 08:04

import django.core.validators
import django.utils.timezone
import django_countries.fields
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Création"),
                            ("UPDATE", "Mise à jour"),
                            ("DELETE", "Suppression"),
                            ("APPROVE", "Approbation"),
                            ("REJECT", "Rejet"),
                            ("REFUND", "Remboursement"),
                            ("PAYOUT", "Versement"),
                            ("LOGIN", "Connexion"),
                            ("LOGOUT", "Déconnexion"),
                            ("WALLET_LOGIN", "Connexion portefeuille"),
                            ("WALLET_PIN_CHANGE", "Changement PIN portefeuille"),
                            (
                                "WALLET_SECURITY_CHANGE",
                                "Changement sécurité portefeuille",
                            ),
                            ("WALLET_CREATION", "Création portefeuille"),
                        ],
                        max_length=50,
                        verbose_name="Type d'action",
                    ),
                ),
                (
                    "action_description",
                    models.TextField(verbose_name="Description de l'action"),
                ),
                (
                    "object_type",
                    models.CharField(max_length=100, verbose_name="Type d'objet"),
                ),
                (
                    "object_id",
                    models.CharField(max_length=100, verbose_name="ID de l'objet"),
                ),
                (
                    "old_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Anciennes données"
                    ),
                ),
                (
                    "new_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Nouvelles données"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Journal d'audit",
                "verbose_name_plural": "Journaux d'audit",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="Taux de commission",
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        verbose_name="Montant commission",
                    ),
                ),
                (
                    "vat_on_commission",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        verbose_name="TVA sur commission",
                    ),
                ),
                (
                    "net_commission",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Commission nette"
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="Commission payée"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Payé le"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Commission",
                "verbose_name_plural": "Commissions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Code"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Pourcentage"),
                            ("FIXED_AMOUNT", "Montant fixe"),
                            ("FREE_SHIPPING", "Livraison gratuite"),
                        ],
                        max_length=20,
                        verbose_name="Type de réduction",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Valeur de la réduction",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EUR", "€"),
                            ("USD", "$"),
                            ("GBP", "£"),
                            ("MAD", "DH"),
                            ("XOF", "CFA"),
                            ("XAF", "FCFA"),
                            ("TND", "DT"),
                            ("DZD", "DA"),
                        ],
                        max_length=3,
                        null=True,
                        verbose_name="Devise (pour montant fixe)",
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="Valide à partir de")),
                ("valid_until", models.DateTimeField(verbose_name="Valide jusqu'à")),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Utilisations maximum"
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(default=0, verbose_name="Utilisations"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="Code devise"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Nom de la devise"),
                ),
                ("symbol", models.CharField(max_length=5, verbose_name="Symbole")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Taux de change",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Devise",
                "verbose_name_plural": "Devises",
                "ordering": ["display_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(
                        choices=[
                            ("EUR", "€"),
                            ("USD", "$"),
                            ("GBP", "£"),
                            ("MAD", "DH"),
                            ("XOF", "CFA"),
                            ("XAF", "FCFA"),
                            ("TND", "DT"),
                            ("DZD", "DA"),
                        ],
                        max_length=3,
                        verbose_name="Devise de base",
                    ),
                ),
                (
                    "target_currency",
                    models.CharField(
                        choices=[
                            ("EUR", "€"),
                            ("USD", "$"),
                            ("GBP", "£"),
                            ("MAD", "DH"),
                            ("XOF", "CFA"),
                            ("XAF", "FCFA"),
                            ("TND", "DT"),
                            ("DZD", "DA"),
                        ],
                        max_length=3,
                        verbose_name="Devise cible",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=6, max_digits=10, verbose_name="Taux"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                ("source", models.CharField(max_length=50, verbose_name="Source")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Taux de change",
                "verbose_name_plural": "Taux de change",
            },
        ),
        migrations.CreateModel(
            name="FraudAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Détecté le"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Faible"),
                            ("MEDIUM", "Moyen"),
                            ("HIGH", "Élevé"),
                            ("CRITICAL", "Critique"),
                        ],
                        max_length=20,
                        verbose_name="Sévérité",
                    ),
                ),
                (
                    "fraud_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Score de fraude"
                    ),
                ),
                ("reasons", models.JSONField(verbose_name="Raisons de l'alerte")),
                (
                    "action_taken",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Action prise"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Revu le"),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, verbose_name="Notes de revue"),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Résolu"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Résolu le"
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="Notes de résolution"),
                ),
            ],
            options={
                "verbose_name": "Alerte de fraude",
                "verbose_name_plural": "Alertes de fraude",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Numéro de facture",
                    ),
                ),
                (
                    "billing_name",
                    models.CharField(max_length=200, verbose_name="Nom de facturation"),
                ),
                (
                    "billing_address",
                    models.TextField(verbose_name="Adresse de facturation"),
                ),
                (
                    "billing_country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Pays de facturation"
                    ),
                ),
                (
                    "billing_vat",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro TVA"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Sous-total"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Taux TVA (%)",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Montant TVA"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Montant total"
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de facture",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Date d'échéance")),
                (
                    "paid_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de paiement"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("SENT", "Envoyée"),
                            ("PAID", "Payée"),
                            ("OVERDUE", "En retard"),
                            ("CANCELLED", "Annulée"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notes additionnelles"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="invoices/%Y/%m/",
                        verbose_name="Fichier PDF",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Prix unitaire"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Taux de taxe (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Élément de facture",
                "verbose_name_plural": "Éléments de facture",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_four",
                    models.CharField(max_length=4, verbose_name="4 derniers chiffres"),
                ),
                (
                    "expiry_month",
                    models.CharField(max_length=2, verbose_name="Mois d'expiration"),
                ),
                (
                    "expiry_year",
                    models.CharField(max_length=4, verbose_name="Année d'expiration"),
                ),
                (
                    "cardholder_name",
                    models.CharField(max_length=100, verbose_name="Nom du titulaire"),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("VISA", "Visa"),
                            ("MASTERCARD", "Mastercard"),
                            ("AMEX", "American Express"),
                            ("DISCOVER", "Discover"),
                            ("DINERS", "Diners Club"),
                            ("JCB", "JCB"),
                            ("UNKNOWN", "Inconnu"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                        verbose_name="Type de carte",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Token sécurisé"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="STRIPE", max_length=50, verbose_name="Fournisseur"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Carte par défaut"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Vérifiée"),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière utilisation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Carte bancaire",
                "verbose_name_plural": "Cartes bancaires",
                "ordering": ["-is_default", "-last_used"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("CARD", "Carte bancaire"),
                            ("BANK_ACCOUNT", "Compte bancaire"),
                            ("DIGITAL_WALLET", "Portefeuille numérique"),
                            ("MOBILE_MONEY", "Mobile Money"),
                        ],
                        max_length=20,
                        verbose_name="Type de méthode",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Méthode par défaut"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Vérifiée"),
                ),
                (
                    "encrypted_data",
                    models.TextField(editable=False, verbose_name="Données chiffrées"),
                ),
                (
                    "encryption_key_id",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        verbose_name="ID clé de chiffrement",
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière utilisation"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Méthode de paiement",
                "verbose_name_plural": "Méthodes de paiement",
                "ordering": ["-is_default", "-last_used"],
            },
        ),
        migrations.CreateModel(
            name="PaymentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="ID de session",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Montant"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "€"),
                            ("USD", "$"),
                            ("GBP", "£"),
                            ("MAD", "DH"),
                            ("XOF", "CFA"),
                            ("XAF", "FCFA"),
                            ("TND", "DT"),
                            ("DZD", "DA"),
                        ],
                        default="EUR",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CREDIT_CARD", "Carte de crédit"),
                            ("DEBIT_CARD", "Carte de débit"),
                            ("PAYPAL", "PayPal"),
                            ("STRIPE", "Stripe"),
                            ("BANK_TRANSFER", "Virement bancaire"),
                            ("CASH", "Espèces"),
                            ("EBI3_WALLET", "Portefeuille Ebi3"),
                            ("PAYSTACK", "Paystack"),
                            ("CINETPAY", "CinetPay"),
                            ("ORANGE_MONEY", "Orange Money"),
                            ("MTN_MONEY", "MTN Money"),
                        ],
                        max_length=20,
                        verbose_name="Méthode de paiement",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("PROCESSING", "En traitement"),
                            ("COMPLETED", "Complété"),
                            ("FAILED", "Échoué"),
                            ("REFUNDED", "Remboursé"),
                            ("PARTIALLY_REFUNDED", "Partiellement remboursé"),
                            ("CANCELLED", "Annulé"),
                            ("EXPIRED", "Expiré"),
                            ("DISPUTED", "En litige"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Métadonnées"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expire à")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Session de paiement",
                "verbose_name_plural": "Sessions de paiement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="ID transaction",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Référence transaction",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Montant",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "€"),
                            ("USD", "$"),
                            ("GBP", "£"),
                            ("MAD", "DH"),
                            ("XOF", "CFA"),
                            ("XAF", "FCFA"),
                            ("TND", "DT"),
                            ("DZD", "DA"),
                        ],
                        default="EUR",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Taux de change",
                    ),
                ),
                (
                    "amount_converted",
                    models.DecimalField(
                        decimal_places=4,
                        editable=False,
                        max_digits=12,
                        verbose_name="Montant converti",
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        verbose_name="Frais de transaction",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        verbose_name="Montant taxes",
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=4,
                        editable=False,
                        max_digits=12,
                        verbose_name="Montant net",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("AD_PURCHASE", "Achat annonce"),
                            ("AD_FEATURED", "Mise en vedette"),
                            ("AD_RESERVATION", "Réservation annonce"),
                            ("MISSION_PAYMENT", "Paiement mission"),
                            ("CARRIER_PAYOUT", "Versement transporteur"),
                            ("COMMISSION", "Commission Ebi3"),
                            ("WALLET_TOPUP", "Rechargement portefeuille"),
                            ("WALLET_TRANSFER", "Transfert portefeuille"),
                            ("REFUND", "Remboursement"),
                            ("SUBSCRIPTION", "Abonnement"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de paiement",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CREDIT_CARD", "Carte de crédit"),
                            ("DEBIT_CARD", "Carte de débit"),
                            ("PAYPAL", "PayPal"),
                            ("STRIPE", "Stripe"),
                            ("BANK_TRANSFER", "Virement bancaire"),
                            ("CASH", "Espèces"),
                            ("EBI3_WALLET", "Portefeuille Ebi3"),
                            ("PAYSTACK", "Paystack"),
                            ("CINETPAY", "CinetPay"),
                            ("ORANGE_MONEY", "Orange Money"),
                            ("MTN_MONEY", "MTN Money"),
                        ],
                        max_length=20,
                        verbose_name="Méthode de paiement",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("PROCESSING", "En traitement"),
                            ("COMPLETED", "Complété"),
                            ("FAILED", "Échoué"),
                            ("REFUNDED", "Remboursé"),
                            ("PARTIALLY_REFUNDED", "Partiellement remboursé"),
                            ("CANCELLED", "Annulé"),
                            ("EXPIRED", "Expiré"),
                            ("DISPUTED", "En litige"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "payment_token",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        verbose_name="Token de paiement",
                    ),
                ),
                (
                    "payment_gateway_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID passerelle"
                    ),
                ),
                (
                    "payment_gateway_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données passerelle"
                    ),
                ),
                (
                    "three_d_secure",
                    models.BooleanField(default=False, verbose_name="3D Secure activé"),
                ),
                (
                    "three_d_secure_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NOT_SUPPORTED", "Non supporté"),
                            ("SUCCESS", "Succès"),
                            ("FAILED", "Échoué"),
                            ("SKIPPED", "Ignoré"),
                        ],
                        max_length=20,
                        verbose_name="Statut 3D Secure",
                    ),
                ),
                (
                    "fraud_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Score fraude",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "risk_checked",
                    models.BooleanField(
                        default=False, verbose_name="Contrôle risque effectué"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(blank=True, null=True, verbose_name="Métadonnées"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
            ],
            options={
                "verbose_name": "Transaction de paiement",
                "verbose_name_plural": "Transactions de paiement",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_view_all_transactions", "Peut voir toutes les transactions"),
                    ("can_refund_transactions", "Peut effectuer des remboursements"),
                    (
                        "can_export_financial_data",
                        "Peut exporter les données financières",
                    ),
                    ("can_manage_fraud_detection", "Peut gérer la détection de fraude"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payout_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="ID versement",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Montant",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "€"),
                            ("USD", "$"),
                            ("GBP", "£"),
                            ("MAD", "DH"),
                            ("XOF", "CFA"),
                            ("XAF", "FCFA"),
                            ("TND", "DT"),
                            ("DZD", "DA"),
                        ],
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        verbose_name="Frais de versement",
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Montant net"
                    ),
                ),
                (
                    "payout_method",
                    models.CharField(
                        choices=[
                            ("BANK_TRANSFER", "Virement bancaire"),
                            ("PAYPAL", "PayPal"),
                            ("STRIPE_CONNECT", "Stripe Connect"),
                            ("EBI3_WALLET", "Portefeuille Ebi3"),
                            ("WESTERN_UNION", "Western Union"),
                            ("MONEYGRAM", "MoneyGram"),
                        ],
                        max_length=20,
                        verbose_name="Méthode de versement",
                    ),
                ),
                (
                    "beneficiary_data",
                    models.TextField(
                        editable=False, verbose_name="Données bénéficiaire"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("PROCESSING", "En traitement"),
                            ("COMPLETED", "Complété"),
                            ("FAILED", "Échoué"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "payout_gateway_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="ID versement passerelle",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Versement",
                "verbose_name_plural": "Versements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom du plan")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Prix"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "€"),
                            ("USD", "$"),
                            ("GBP", "£"),
                            ("MAD", "DH"),
                            ("XOF", "CFA"),
                            ("XAF", "FCFA"),
                            ("TND", "DT"),
                            ("DZD", "DA"),
                        ],
                        default="EUR",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("DAILY", "Quotidien"),
                            ("WEEKLY", "Hebdomadaire"),
                            ("MONTHLY", "Mensuel"),
                            ("QUARTERLY", "Trimestriel"),
                            ("SEMI_ANNUAL", "Semestriel"),
                            ("ANNUAL", "Annuel"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                        verbose_name="Intervalle",
                    ),
                ),
                (
                    "interval_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Nombre d'intervalles"
                    ),
                ),
                (
                    "trial_period_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Période d'essai (jours)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "features",
                    models.JSONField(default=dict, verbose_name="Fonctionnalités"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plan d'abonnement",
                "verbose_name_plural": "Plans d'abonnement",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refund_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="ID remboursement",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Montant remboursé",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "€"),
                            ("USD", "$"),
                            ("GBP", "£"),
                            ("MAD", "DH"),
                            ("XOF", "CFA"),
                            ("XAF", "FCFA"),
                            ("TND", "DT"),
                            ("DZD", "DA"),
                        ],
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("DUPLICATE_CHARGE", "Double facturation"),
                            ("UNAUTHORIZED", "Non autorisé"),
                            ("PRODUCT_DEFECT", "Défaut produit"),
                            ("NOT_RECEIVED", "Non reçu"),
                            ("WRONG_AMOUNT", "Mauvais montant"),
                            ("CANCELLED", "Annulé par client"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Raison",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description détaillée")),
                (
                    "evidence",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="refunds/evidence/",
                        verbose_name="Preuve",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Demandé"),
                            ("UNDER_REVIEW", "En revue"),
                            ("APPROVED", "Approuvé"),
                            ("REJECTED", "Rejeté"),
                            ("PROCESSING", "En traitement"),
                            ("COMPLETED", "Complété"),
                            ("FAILED", "Échoué"),
                        ],
                        default="REQUESTED",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, verbose_name="Notes de revue"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Raison du rejet"),
                ),
                (
                    "refund_gateway_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="ID remboursement passerelle",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Remboursement",
                "verbose_name_plural": "Remboursements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("ACTIVE", "Actif"),
                            ("PAST_DUE", "En retard"),
                            ("CANCELLED", "Annulé"),
                            ("EXPIRED", "Expiré"),
                            ("SUSPENDED", "Suspendu"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(verbose_name="Début de la période actuelle"),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(verbose_name="Fin de la période actuelle"),
                ),
                (
                    "cancel_at_period_end",
                    models.BooleanField(
                        default=False, verbose_name="Annuler à la fin de la période"
                    ),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Annulé le"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Métadonnées"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Abonnement",
                "verbose_name_plural": "Abonnements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        max_length=2, unique=True, verbose_name="Pays"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Taux TVA (%)"
                    ),
                ),
                (
                    "tax_name",
                    models.CharField(max_length=100, verbose_name="Nom de la taxe"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "exempt_categories",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Catégories exemptées"
                    ),
                ),
                (
                    "minimum_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Montant minimum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taxe",
                "verbose_name_plural": "Taxes",
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Solde",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "€"),
                            ("USD", "$"),
                            ("GBP", "£"),
                            ("MAD", "DH"),
                            ("XOF", "CFA"),
                            ("XAF", "FCFA"),
                            ("TND", "DT"),
                            ("DZD", "DA"),
                        ],
                        default="EUR",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "reserved_balance",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        verbose_name="Solde réservé",
                    ),
                ),
                (
                    "available_balance",
                    models.DecimalField(
                        decimal_places=4,
                        editable=False,
                        max_digits=12,
                        verbose_name="Solde disponible",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Actif"),
                            ("SUSPENDED", "Suspendu"),
                            ("LOCKED", "Verrouillé"),
                            ("CLOSED", "Fermé"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "daily_limit",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1000"),
                        max_digits=12,
                        verbose_name="Limite quotidienne",
                    ),
                ),
                (
                    "monthly_limit",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("5000"),
                        max_digits=12,
                        verbose_name="Limite mensuelle",
                    ),
                ),
                (
                    "pin_hash",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        verbose_name="Hash du PIN",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(default=False, verbose_name="Verrouillé"),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verrouillé jusqu'à"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Vérifié"),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Score de risque",
                    ),
                ),
                (
                    "blocked_balance",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        verbose_name="Solde bloqué",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Portefeuille",
                "verbose_name_plural": "Portefeuilles",
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Montant"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Dépôt"),
                            ("WITHDRAWAL", "Retrait"),
                            ("TRANSFER", "Transfert"),
                            ("PAYMENT", "Paiement"),
                            ("REFUND", "Remboursement"),
                            ("COMMISSION", "Commission"),
                            ("BLOCK", "Blocage"),
                            ("CREDIT", "Crédit"),
                            ("DEBIT", "Débit"),
                        ],
                        max_length=20,
                        verbose_name="Type de transaction",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("PROCESSING", "En traitement"),
                            ("COMPLETED", "Complété"),
                            ("FAILED", "Échoué"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, null=True, verbose_name="Métadonnées"),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Solde avant"
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Solde après"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Transaction portefeuille",
                "verbose_name_plural": "Transactions portefeuille",
                "ordering": ["-created_at"],
            },
        ),
    ]
