# Generated by Django 6.0 on 2026-01-15 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ads", "0002_initial"),
        ("carriers", "0002_initial"),
        ("logistics", "0002_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="exchangerate",
            unique_together={("base_currency", "target_currency")},
        ),
        migrations.AddField(
            model_name="fraudalert",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Revu par",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="payments.invoice",
                verbose_name="Facture",
            ),
        ),
        migrations.AddField(
            model_name="paymentcard",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_cards",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_methods",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="paymentsession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="ad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="ads.ad",
                verbose_name="Annonce liée",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="carrier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="carriers.carrier",
                verbose_name="Transporteur lié",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="mission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="logistics.mission",
                verbose_name="Mission liée",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="payee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_received",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Bénéficiaire",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="payer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_sent",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Payeur",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="transport_proposal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="logistics.transportproposal",
                verbose_name="Proposition transport liée",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="transaction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice",
                to="payments.paymenttransaction",
                verbose_name="Transaction",
            ),
        ),
        migrations.AddField(
            model_name="fraudalert",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fraud_alerts",
                to="payments.paymenttransaction",
                verbose_name="Transaction",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="transaction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commission",
                to="payments.paymenttransaction",
                verbose_name="Transaction",
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="transactions",
            field=models.ManyToManyField(
                related_name="payouts",
                to="payments.paymenttransaction",
                verbose_name="Transactions incluses",
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payouts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Bénéficiaire",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refunds_requested",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Demandé par",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds_reviewed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Revu par",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refunds",
                to="payments.paymenttransaction",
                verbose_name="Transaction originale",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="payments.plan",
                verbose_name="Plan",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="payment_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wallet_transactions",
                to="payments.paymenttransaction",
                verbose_name="Transaction de paiement liée",
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="payments.wallet",
                verbose_name="Portefeuille",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "created_at"], name="payments_au_user_id_52d5af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["object_type", "object_id"],
                name="payments_au_object__ed6e2c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymentcard",
            unique_together={("user", "token")},
        ),
        migrations.AlterUniqueTogether(
            name="paymentmethod",
            unique_together={("user", "encryption_key_id")},
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["status", "created_at"], name="payments_pa_status_c4e513_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["payer", "status"], name="payments_pa_payer_i_2437ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["payee", "status"], name="payments_pa_payee_i_59280c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["payment_type", "status"], name="payments_pa_payment_c7d4e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["reference"], name="payments_pa_referen_72073c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["payment_gateway_id"], name="payments_pa_payment_8e4726_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="payments_in_invoice_3fa711_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["status", "due_date"], name="payments_in_status_68daea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payout",
            index=models.Index(
                fields=["status", "created_at"], name="payments_pa_status_2b7eb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payout",
            index=models.Index(
                fields=["user", "status"], name="payments_pa_user_id_024e9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["status", "created_at"], name="payments_re_status_698972_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["transaction", "status"], name="payments_re_transac_a3e947_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["user", "status"], name="payments_su_user_id_058311_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["current_period_end"], name="payments_su_current_d26b0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["wallet", "created_at"], name="payments_wa_wallet__9a8a81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["transaction_type", "created_at"],
                name="payments_wa_transac_b3760c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["status", "created_at"], name="payments_wa_status_d9255e_idx"
            ),
        ),
    ]
