# Generated by Django 6.0 on 2026-01-15 08:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ads", "0001_initial"),
        ("carriers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogisticsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Taux de commission (%)",
                    ),
                ),
                (
                    "reservation_expiry_hours",
                    models.PositiveIntegerField(
                        default=48, verbose_name="Expiration réservation (heures)"
                    ),
                ),
                (
                    "proposal_expiry_days",
                    models.PositiveIntegerField(
                        default=7, verbose_name="Expiration proposition (jours)"
                    ),
                ),
                (
                    "payment_hold_days",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Rétention paiement (jours)"
                    ),
                ),
                (
                    "auto_release_payment",
                    models.BooleanField(
                        default=True, verbose_name="Libération automatique paiement"
                    ),
                ),
                (
                    "notify_on_reservation",
                    models.BooleanField(
                        default=True, verbose_name="Notifier nouvelle réservation"
                    ),
                ),
                (
                    "notify_on_status_change",
                    models.BooleanField(
                        default=True, verbose_name="Notifier changement statut"
                    ),
                ),
                (
                    "notify_before_expiry",
                    models.BooleanField(
                        default=True, verbose_name="Notifier avant expiration"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètre logistique",
                "verbose_name_plural": "Paramètres logistiques",
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_city",
                    models.CharField(max_length=100, verbose_name="Ville de départ"),
                ),
                (
                    "start_address",
                    models.TextField(blank=True, verbose_name="Adresse de départ"),
                ),
                (
                    "end_city",
                    models.CharField(max_length=100, verbose_name="Ville d'arrivée"),
                ),
                (
                    "end_address",
                    models.TextField(blank=True, verbose_name="Adresse d'arrivée"),
                ),
                ("departure_date", models.DateField(verbose_name="Date de départ")),
                ("arrival_date", models.DateField(verbose_name="Date d'arrivée")),
                (
                    "max_weight",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Poids maximum (kg)",
                    ),
                ),
                (
                    "max_volume",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Volume maximum (m³)",
                    ),
                ),
                (
                    "available_weight",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Poids disponible (kg)",
                    ),
                ),
                (
                    "available_volume",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Volume disponible (m³)",
                    ),
                ),
                (
                    "fixed_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix fixe",
                    ),
                ),
                (
                    "price_per_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix par kg",
                    ),
                ),
                (
                    "price_per_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix par m³",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("FULL", "Complète"),
                            ("IN_TRANSIT", "En transit"),
                            ("COMPLETED", "Terminée"),
                            ("CANCELLED", "Annulée"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "includes_insurance",
                    models.BooleanField(
                        default=False, verbose_name="Assurance incluse"
                    ),
                ),
                (
                    "includes_packaging",
                    models.BooleanField(default=False, verbose_name="Emballage inclus"),
                ),
                (
                    "includes_loading",
                    models.BooleanField(
                        default=False, verbose_name="Chargement inclus"
                    ),
                ),
                (
                    "includes_unloading",
                    models.BooleanField(
                        default=False, verbose_name="Déchargement inclus"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "special_conditions",
                    models.TextField(blank=True, verbose_name="Conditions spéciales"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Mis en avant"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de vues"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Route",
                "verbose_name_plural": "Routes",
                "ordering": ["departure_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PICKUP_SCHEDULED", "Prise en charge planifiée"),
                            ("PICKUP_CONFIRMED", "Prise en charge confirmée"),
                            ("PICKUP_COMPLETED", "Prise en charge effectuée"),
                            ("IN_TRANSIT", "En transit"),
                            ("ARRIVED_AT_HUB", "Arrivé au centre de tri"),
                            ("DEPARTED_FROM_HUB", "Départ du centre de tri"),
                            ("OUT_FOR_DELIVERY", "En cours de livraison"),
                            ("DELIVERY_ATTEMPTED", "Tentative de livraison"),
                            ("DELIVERY_RESCHEDULED", "Livraison reprogrammée"),
                            ("DELIVERED", "Livré"),
                            ("DELAYED", "Retardé"),
                            ("CUSTOMS_CLEARANCE", "Dédouanement"),
                            ("CUSTOMS_HELD", "Retenu en douane"),
                            ("ISSUE_REPORTED", "Problème signalé"),
                            ("ISSUE_RESOLVED", "Problème résolu"),
                        ],
                        max_length=50,
                        verbose_name="Type d'événement",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Localisation"
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Latitude"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Longitude"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tracking/events/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement de suivi",
                "verbose_name_plural": "Événements de suivi",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransportProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proposed_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix proposé",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Message")),
                (
                    "estimated_pickup_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date de prise en charge estimée",
                    ),
                ),
                (
                    "estimated_delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de livraison estimée"
                    ),
                ),
                (
                    "includes_insurance",
                    models.BooleanField(
                        default=False, verbose_name="Assurance incluse"
                    ),
                ),
                (
                    "insurance_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valeur assurée",
                    ),
                ),
                (
                    "includes_packaging",
                    models.BooleanField(default=False, verbose_name="Emballage inclus"),
                ),
                (
                    "includes_loading",
                    models.BooleanField(
                        default=False, verbose_name="Chargement inclus"
                    ),
                ),
                (
                    "includes_unloading",
                    models.BooleanField(
                        default=False, verbose_name="Déchargement inclus"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("ACCEPTED", "Acceptée"),
                            ("REJECTED", "Rejetée"),
                            ("EXPIRED", "Expirée"),
                            ("CANCELLED", "Annulée"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Date d'expiration")),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de réponse"
                    ),
                ),
                (
                    "response_message",
                    models.TextField(blank=True, verbose_name="Message de réponse"),
                ),
            ],
            options={
                "verbose_name": "Proposition de transport",
                "verbose_name_plural": "Propositions de transport",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Planifiée"),
                            ("PICKUP_PENDING", "En attente de prise en charge"),
                            ("PICKED_UP", "Pris en charge"),
                            ("IN_TRANSIT", "En transit"),
                            ("AT_HUB", "Au centre de tri"),
                            ("OUT_FOR_DELIVERY", "En cours de livraison"),
                            ("DELIVERY_PENDING", "En attente de livraison"),
                            ("DELIVERED", "Livrée"),
                            ("CANCELLED", "Annulée"),
                            ("DELAYED", "Retardée"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "current_location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Localisation actuelle"
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Latitude"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Longitude"),
                ),
                (
                    "scheduled_pickup",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Prise en charge planifiée"
                    ),
                ),
                (
                    "actual_pickup",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Prise en charge réelle"
                    ),
                ),
                (
                    "estimated_delivery",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Livraison estimée"
                    ),
                ),
                (
                    "actual_delivery",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Livraison réelle"
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Distance (km)",
                    ),
                ),
                (
                    "pickup_confirmation",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="missions/pickup_confirmations/",
                        verbose_name="Confirmation prise en charge",
                    ),
                ),
                (
                    "delivery_confirmation",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="missions/delivery_confirmations/",
                        verbose_name="Confirmation livraison",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "delay_reason",
                    models.TextField(blank=True, verbose_name="Raison du retard"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to="carriers.carrier",
                        verbose_name="Transporteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mission",
                "verbose_name_plural": "Missions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logistics_option",
                    models.CharField(
                        choices=[
                            ("P2P_DIRECT", "Direct entre particuliers"),
                            ("WITH_CARRIER", "Avec transporteur"),
                            ("WITH_EXPAT_CARRIER", "Avec expatrié-transporteur"),
                        ],
                        max_length=20,
                        verbose_name="Option logistique",
                    ),
                ),
                (
                    "pickup_address",
                    models.TextField(
                        blank=True, verbose_name="Adresse de prise en charge"
                    ),
                ),
                (
                    "delivery_address",
                    models.TextField(blank=True, verbose_name="Adresse de livraison"),
                ),
                (
                    "pickup_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de prise en charge"
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de livraison estimée"
                    ),
                ),
                (
                    "actual_delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de livraison réelle"
                    ),
                ),
                (
                    "price_agreed",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix convenu",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Coût du transport",
                    ),
                ),
                (
                    "insurance_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Coût assurance",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix total",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("CONFIRMED", "Confirmée"),
                            ("PAYMENT_PENDING", "Paiement en attente"),
                            ("PAID", "Payée"),
                            ("IN_TRANSIT", "En transit"),
                            ("DELIVERED", "Livrée"),
                            ("CANCELLED", "Annulée"),
                            ("DISPUTED", "En litige"),
                            ("REFUNDED", "Remboursée"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Numéro de suivi"
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Payé")),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Méthode de paiement"
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de paiement"
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence paiement"
                    ),
                ),
                (
                    "requires_insurance",
                    models.BooleanField(
                        default=False, verbose_name="Assurance requise"
                    ),
                ),
                (
                    "insurance_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valeur assurée",
                    ),
                ),
                (
                    "requires_packaging",
                    models.BooleanField(default=False, verbose_name="Emballage requis"),
                ),
                (
                    "packaging_details",
                    models.TextField(blank=True, verbose_name="Détails emballage"),
                ),
                (
                    "buyer_notes",
                    models.TextField(blank=True, verbose_name="Notes acheteur"),
                ),
                (
                    "seller_notes",
                    models.TextField(blank=True, verbose_name="Notes vendeur"),
                ),
                (
                    "carrier_notes",
                    models.TextField(blank=True, verbose_name="Notes transporteur"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'annulation"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="Raison annulation"),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="ads.ad",
                        verbose_name="Annonce",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réservation",
                "verbose_name_plural": "Réservations",
                "ordering": ["-created_at"],
            },
        ),
    ]
