# Generated by Django 6.0 on 2025-12-31 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ads", "0002_initial"),
        ("carriers", "0002_initial"),
        ("core", "0001_initial"),
        ("logistics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Acheteur",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_reservations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Annulé par",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="carrier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logistics_routes",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="reservation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission",
                to="logistics.reservation",
                verbose_name="Réservation",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="end_country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrival_routes",
                to="core.country",
                verbose_name="Pays d'arrivée",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="start_country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departure_routes",
                to="core.country",
                verbose_name="Pays de départ",
            ),
        ),
        migrations.AddField(
            model_name="trackingevent",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="trackingevent",
            name="mission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracking_events",
                to="logistics.mission",
                verbose_name="Mission",
            ),
        ),
        migrations.AddField(
            model_name="transportproposal",
            name="ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transport_proposals",
                to="ads.ad",
                verbose_name="Annonce",
            ),
        ),
        migrations.AddField(
            model_name="transportproposal",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposals",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["status"], name="logistics_r_status_bc9948_idx"),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["buyer", "status"], name="logistics_r_buyer_i_b541fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["ad", "status"], name="logistics_r_ad_id_2abdeb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["created_at"], name="logistics_r_created_eb71a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mission",
            index=models.Index(fields=["status"], name="logistics_m_status_270aca_idx"),
        ),
        migrations.AddIndex(
            model_name="mission",
            index=models.Index(
                fields=["carrier", "status"], name="logistics_m_carrier_f902c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mission",
            index=models.Index(
                fields=["estimated_delivery"], name="logistics_m_estimat_ee54d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(fields=["status"], name="logistics_r_status_7d224f_idx"),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["departure_date"], name="logistics_r_departu_45551c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["carrier", "status"], name="logistics_r_carrier_f89289_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["start_country", "end_country"],
                name="logistics_r_start_c_14ae17_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trackingevent",
            index=models.Index(
                fields=["mission", "created_at"], name="logistics_t_mission_e9c461_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trackingevent",
            index=models.Index(
                fields=["event_type"], name="logistics_t_event_t_ebffed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transportproposal",
            index=models.Index(fields=["status"], name="logistics_t_status_04e514_idx"),
        ),
        migrations.AddIndex(
            model_name="transportproposal",
            index=models.Index(
                fields=["ad", "status"], name="logistics_t_ad_id_b915a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transportproposal",
            index=models.Index(
                fields=["carrier", "status"], name="logistics_t_carrier_1e3904_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transportproposal",
            index=models.Index(
                fields=["expires_at"], name="logistics_t_expires_b2ddac_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transportproposal",
            unique_together={("ad", "carrier")},
        ),
    ]
