# Generated by Django 6.0 on 2026-01-15 08:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("BUYER", "Acheteur"),
                            ("SELLER", "Vendeur"),
                            ("CARRIER", "Transporteur Professionnel"),
                            ("CARRIER_PERSONAL", "Transporteur Particulier"),
                            ("ADMIN", "Administrateur"),
                            ("MODERATOR", "Modérateur"),
                        ],
                        default="BUYER",
                        max_length=20,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Numéro de téléphone",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True, verbose_name="Pays"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Compte vérifié"),
                ),
                (
                    "kyc_verified",
                    models.BooleanField(default=False, verbose_name="KYC vérifié"),
                ),
                (
                    "email_verified",
                    models.BooleanField(default=False, verbose_name="Email vérifié"),
                ),
                (
                    "phone_verified",
                    models.BooleanField(
                        default=False, verbose_name="Téléphone vérifié"
                    ),
                ),
                (
                    "kyc_submitted",
                    models.BooleanField(default=False, verbose_name="KYC soumis"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("ar", "العربية"),
                            ("fr", "Français"),
                            ("en", "English"),
                            ("de", "Deutsch"),
                            ("it", "Italiano"),
                            ("es", "Español"),
                            ("pt", "Português"),
                            ("pl", "Polski"),
                        ],
                        default="fr",
                        max_length=10,
                        verbose_name="Langue préférée",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, verbose_name="Disponible pour des missions"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        verbose_name="Note moyenne",
                    ),
                ),
                (
                    "total_reviews",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre total d'avis"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculin"), ("F", "Féminin"), ("O", "Autre")],
                        max_length=10,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nom de l'entreprise"
                    ),
                ),
                (
                    "company_registration",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Numéro d'immatriculation",
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Numéro fiscal"
                    ),
                ),
                (
                    "id_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/id/",
                        verbose_name="Document d'identité",
                    ),
                ),
                (
                    "proof_of_address",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/address/",
                        verbose_name="Justificatif de domicile",
                    ),
                ),
                (
                    "company_registration_doc",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/company/",
                        verbose_name="Document d'immatriculation",
                    ),
                ),
                (
                    "country_of_origin",
                    django_countries.fields.CountryField(
                        blank=True,
                        max_length=2,
                        null=True,
                        verbose_name="Pays d'origine",
                    ),
                ),
                (
                    "country_of_residence",
                    django_countries.fields.CountryField(
                        blank=True,
                        max_length=2,
                        null=True,
                        verbose_name="Pays de résidence",
                    ),
                ),
                (
                    "is_expatriate",
                    models.BooleanField(default=False, verbose_name="Est un expatrié"),
                ),
                (
                    "total_ads",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre total d'annonces"
                    ),
                ),
                (
                    "successful_transactions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Transactions réussies"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil utilisateur",
                "verbose_name_plural": "Profils utilisateurs",
            },
        ),
    ]
