# Generated by Django 6.0 on 2026-01-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="phone",
            new_name="phone",
        ),
    ]
