# Generated by Django 6.0 on 2025-12-31 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("subject", models.CharField(max_length=200, verbose_name="Sujet")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Nouveau"),
                            ("IN_PROGRESS", "En cours"),
                            ("RESOLVED", "Résolu"),
                            ("SPAM", "Spam"),
                        ],
                        default="NEW",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, verbose_name="Notes de l'administrateur"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Message de contact",
                "verbose_name_plural": "Messages de contact",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=2, unique=True, verbose_name="Code ISO"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nom en arabe"
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nom en français"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nom en anglais"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Le pays est-il disponible sur la plateforme ?",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "is_departure",
                    models.BooleanField(
                        default=True,
                        help_text="Peut être un pays de départ",
                        verbose_name="Pays de départ",
                    ),
                ),
                (
                    "is_destination",
                    models.BooleanField(
                        default=True,
                        help_text="Peut être un pays de destination",
                        verbose_name="Pays de destination",
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="Code devise"
                    ),
                ),
                (
                    "currency_symbol",
                    models.CharField(
                        default="€", max_length=10, verbose_name="Symbole devise"
                    ),
                ),
                (
                    "phone_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Indicatif téléphonique"
                    ),
                ),
                (
                    "flag",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="flags/",
                        verbose_name="Drapeau",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pays",
                "verbose_name_plural": "Pays",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Abonné newsletter",
                "verbose_name_plural": "Abonnés newsletter",
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Identifiant unique du paramètre",
                        max_length=100,
                        unique=True,
                        verbose_name="Clé",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom affiché")),
                (
                    "value",
                    models.TextField(
                        help_text="Valeur du paramètre", verbose_name="Valeur"
                    ),
                ),
                (
                    "setting_type",
                    models.CharField(
                        choices=[
                            ("STRING", "Chaîne de caractères"),
                            ("INTEGER", "Nombre entier"),
                            ("BOOLEAN", "Booléen"),
                            ("JSON", "JSON"),
                            ("TEXT", "Texte long"),
                            ("EMAIL", "Email"),
                            ("URL", "URL"),
                        ],
                        default="STRING",
                        max_length=20,
                        verbose_name="Type de paramètre",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        default="general",
                        help_text="Groupe de paramètres",
                        max_length=50,
                        verbose_name="Groupe",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Peut être accédé dans les templates",
                        verbose_name="Public",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée du paramètre",
                        verbose_name="Description",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paramètre du site",
                "verbose_name_plural": "Paramètres du site",
                "ordering": ["group", "key"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500, verbose_name="Question")),
                ("answer", models.TextField(verbose_name="Réponse")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "Général"),
                            ("ACCOUNT", "Compte"),
                            ("ADS", "Annonces"),
                            ("PAYMENTS", "Paiements"),
                            ("LOGISTICS", "Logistique"),
                            ("LEGAL", "Légal"),
                        ],
                        default="GENERAL",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ar", "العربية"),
                            ("fr", "Français"),
                            ("en", "English"),
                            ("de", "Deutsch"),
                            ("it", "Italiano"),
                            ("es", "Español"),
                            ("pt", "Português"),
                            ("pl", "Polski"),
                        ],
                        default="fr",
                        max_length=10,
                        verbose_name="Langue",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["category", "display_order", "question"],
                "indexes": [
                    models.Index(
                        fields=["category", "language", "is_active"],
                        name="core_faq_categor_b657eb_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL de la page",
                        max_length=200,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Contenu de la page (HTML autorisé)",
                        verbose_name="Contenu",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("all", "Toutes les langues"),
                            ("ar", "العربية"),
                            ("fr", "Français"),
                            ("en", "English"),
                            ("de", "Deutsch"),
                            ("it", "Italiano"),
                            ("es", "Español"),
                            ("pt", "Português"),
                            ("pl", "Polski"),
                        ],
                        default="all",
                        max_length=10,
                        verbose_name="Langue",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("PUBLISHED", "Publié"),
                            ("HIDDEN", "Caché"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "show_in_footer",
                    models.BooleanField(
                        default=False, verbose_name="Afficher dans le pied de page"
                    ),
                ),
                (
                    "show_in_menu",
                    models.BooleanField(
                        default=False, verbose_name="Afficher dans le menu"
                    ),
                ),
                (
                    "menu_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre dans le menu"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Titre SEO"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="Description SEO"),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Mots-clés SEO"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ["menu_order", "title"],
                "indexes": [
                    models.Index(
                        fields=["slug", "status"], name="core_page_slug_1c639a_idx"
                    ),
                    models.Index(
                        fields=["language", "status"],
                        name="core_page_languag_c21106_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom de la ville"),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nom en arabe"
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nom en français"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nom en anglais"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "population",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Population"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Fuseau horaire"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="core.country",
                        verbose_name="Pays",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ville",
                "verbose_name_plural": "Villes",
                "ordering": ["country", "display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["country", "is_active"],
                        name="core_city_country_93d21b_idx",
                    ),
                    models.Index(
                        fields=["name", "is_active"], name="core_city_name_85c917_idx"
                    ),
                ],
                "unique_together": {("name", "country")},
            },
        ),
    ]
