# Generated by Django 6.0 on 2026-01-15 08:34

import ads.models
import django.core.validators
import django.utils.timezone
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Titre de l'annonce"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Décrivez votre objet en détail",
                        verbose_name="Description détaillée",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("NEW", "Neuf"),
                            ("LIKE_NEW", "Comme neuf"),
                            ("GOOD", "Bon état"),
                            ("FAIR", "État correct"),
                            ("POOR", "Mauvais état"),
                            ("FOR_PARTS", "Pour pièces"),
                        ],
                        default="GOOD",
                        max_length=20,
                        verbose_name="État de l'objet",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix en devise de départ",
                        max_digits=10,
                        verbose_name="Prix",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "€"),
                            ("USD", "$"),
                            ("GBP", "£"),
                            ("MAD", "DH"),
                            ("XOF", "CFA"),
                        ],
                        default="EUR",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "is_negotiable",
                    models.BooleanField(default=False, verbose_name="Prix négociable"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Poids en kilogrammes",
                        max_digits=8,
                        null=True,
                        verbose_name="Poids (kg)",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Longueur (cm)",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Largeur (cm)",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Hauteur (cm)",
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        editable=False,
                        max_digits=10,
                        null=True,
                        verbose_name="Volume (L)",
                    ),
                ),
                (
                    "country_from",
                    django_countries.fields.CountryField(
                        help_text="Pays où se trouve l'objet",
                        max_length=2,
                        verbose_name="Pays de départ",
                    ),
                ),
                (
                    "city_from",
                    models.CharField(max_length=100, verbose_name="Ville de départ"),
                ),
                (
                    "address_from",
                    models.TextField(blank=True, verbose_name="Adresse de départ"),
                ),
                (
                    "latitude_from",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude départ",
                    ),
                ),
                (
                    "longitude_from",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude départ",
                    ),
                ),
                (
                    "country_to",
                    django_countries.fields.CountryField(
                        help_text="Pays où l'objet doit être livré",
                        max_length=2,
                        verbose_name="Pays de destination",
                    ),
                ),
                (
                    "city_to",
                    models.CharField(
                        max_length=100, verbose_name="Ville de destination"
                    ),
                ),
                (
                    "address_to",
                    models.TextField(blank=True, verbose_name="Adresse de destination"),
                ),
                (
                    "latitude_to",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude destination",
                    ),
                ),
                (
                    "longitude_to",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude destination",
                    ),
                ),
                (
                    "logistics_option",
                    models.CharField(
                        choices=[
                            ("P2P_DIRECT", "Vente directe (P2P)"),
                            ("WITH_CARRIER", "Avec transporteur"),
                            ("WITH_EXPAT_CARRIER", "Avec expatrié-transporteur"),
                        ],
                        default="P2P_DIRECT",
                        max_length=20,
                        verbose_name="Option logistique",
                    ),
                ),
                (
                    "requires_insurance",
                    models.BooleanField(
                        default=False, verbose_name="Requiert assurance"
                    ),
                ),
                (
                    "insurance_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valeur assurée",
                    ),
                ),
                (
                    "fragile_item",
                    models.BooleanField(default=False, verbose_name="Objet fragile"),
                ),
                (
                    "requires_packaging",
                    models.BooleanField(
                        default=False, verbose_name="Requiert emballage"
                    ),
                ),
                (
                    "available_from",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date à partir de laquelle l'objet est disponible",
                        verbose_name="Disponible à partir du",
                    ),
                ),
                (
                    "available_until",
                    models.DateField(
                        blank=True,
                        help_text="Date limite de disponibilité",
                        null=True,
                        verbose_name="Disponible jusqu'au",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("PENDING", "En attente de validation"),
                            ("ACTIVE", "Active"),
                            ("RESERVED", "Réservée"),
                            ("SOLD", "Vendue"),
                            ("EXPIRED", "Expirée"),
                            ("REJECTED", "Rejetée"),
                            ("ARCHIVED", "Archivée"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Annonce en vedette"
                    ),
                ),
                (
                    "featured_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="En vedette jusqu'au"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Raison du rejet"),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Mots-clés SEO"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="Description SEO"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Nombre de vues"
                    ),
                ),
                (
                    "favorite_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Nombre de favoris"
                    ),
                ),
                (
                    "inquiry_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Nombre de demandes"
                    ),
                ),
                (
                    "free_images_allowed",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Nombre de photos gratuites"
                    ),
                ),
                (
                    "paid_images_used",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Photos payantes utilisées"
                    ),
                ),
                (
                    "videos_allowed",
                    models.BooleanField(
                        default=False, verbose_name="Vidéos autorisées"
                    ),
                ),
                (
                    "videos_used",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Vidéos utilisées"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Annonce",
                "verbose_name_plural": "Annonces",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_feature_ad", "Peut mettre en vedette une annonce"),
                    ("can_moderate_ad", "Peut modérer les annonces"),
                    ("can_view_statistics", "Peut voir les statistiques"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=ads.models.ad_image_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp"]
                            ),
                            ads.models.validate_file_size,
                        ],
                        verbose_name="Image",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="ads/thumbnails/",
                        verbose_name="Miniature",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Légende"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Image principale"),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="Image payante"),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("FREE", "Gratuite"),
                            ("PAID", "Payée"),
                            ("PENDING", "En attente"),
                            ("FAILED", "Échouée"),
                        ],
                        default="FREE",
                        max_length=20,
                        verbose_name="Statut du paiement",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence de paiement"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Image d'annonce",
                "verbose_name_plural": "Images d'annonces",
                "ordering": ["is_primary", "display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("SPAM", "Spam ou publicité"),
                            ("FRAUD", "Fraude ou arnaque"),
                            ("INAPPROPRIATE", "Contenu inapproprié"),
                            ("WRONG_CATEGORY", "Mauvaise catégorie"),
                            ("PROHIBITED", "Article prohibé"),
                            ("DUPLICATE", "Annonce en double"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Raison du signalement",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description détaillée"),
                ),
                (
                    "evidence",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reports/",
                        verbose_name="Preuve",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("IN_REVIEW", "En revue"),
                            ("RESOLVED", "Résolu"),
                            ("DISMISSED", "Rejeté"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, verbose_name="Notes de l'administrateur"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Résolu le"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Signalement d'annonce",
                "verbose_name_plural": "Signalements d'annonces",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        upload_to=ads.models.ad_video_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["mp4", "avi", "mov", "wmv", "webm"]
                            ),
                            ads.models.validate_video_size,
                        ],
                        verbose_name="Vidéo",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="ads/video_thumbnails/",
                        verbose_name="Miniature vidéo",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Légende"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(blank=True, null=True, verbose_name="Durée"),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=True, verbose_name="Vidéo payante"),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PAID", "Payée"),
                            ("PENDING", "En attente"),
                            ("FAILED", "Échouée"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut du paiement",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence de paiement"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Vidéo d'annonce",
                "verbose_name_plural": "Vidéos d'annonces",
            },
        ),
        migrations.CreateModel(
            name="AdView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True, max_length=40, verbose_name="Clé de session"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("referer", models.URLField(blank=True, verbose_name="Referer")),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Vue d'annonce",
                "verbose_name_plural": "Vues d'annonces",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=200,
                        verbose_name="Nom de la catégorie",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version du nom",
                        max_length=200,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée de la catégorie",
                        verbose_name="Description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Exemple: fa-mobile, fa-car, fa-home",
                        max_length=100,
                        verbose_name="Icône FontAwesome",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="Image de la catégorie",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Désactiver pour cacher la catégorie",
                        verbose_name="Active",
                    ),
                ),
                (
                    "show_in_menu",
                    models.BooleanField(
                        default=True, verbose_name="Afficher dans le menu"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Plus le nombre est bas, plus c'est prioritaire",
                        verbose_name="Ordre d'affichage",
                    ),
                ),
                (
                    "requires_dimensions",
                    models.BooleanField(
                        default=False,
                        help_text="Les annonces de cette catégorie doivent avoir des dimensions",
                        verbose_name="Requiert dimensions",
                    ),
                ),
                (
                    "requires_weight",
                    models.BooleanField(
                        default=True,
                        help_text="Les annonces de cette catégorie doivent avoir un poids",
                        verbose_name="Requiert poids",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Titre SEO"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="Description SEO"),
                ),
                (
                    "ad_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Nombre d'annonces"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Favori",
                "verbose_name_plural": "Favoris",
                "ordering": ["-created_at"],
            },
        ),
    ]
