# Generated by Django 6.0 on 2026-01-15 08:34

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ads",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vendeur",
            ),
        ),
        migrations.AddField(
            model_name="adimage",
            name="ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="ads.ad",
                verbose_name="Annonce",
            ),
        ),
        migrations.AddField(
            model_name="adreport",
            name="ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="ads.ad",
                verbose_name="Annonce",
            ),
        ),
        migrations.AddField(
            model_name="adreport",
            name="reporter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ad_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Signaleur",
            ),
        ),
        migrations.AddField(
            model_name="adreport",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_ad_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Résolu par",
            ),
        ),
        migrations.AddField(
            model_name="advideo",
            name="ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="ads.ad",
                verbose_name="Annonce",
            ),
        ),
        migrations.AddField(
            model_name="adview",
            name="ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views_tracking",
                to="ads.ad",
                verbose_name="Annonce",
            ),
        ),
        migrations.AddField(
            model_name="adview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ad_views",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="Sélectionnez une catégorie parente si applicable",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="ads.category",
                verbose_name="Catégorie parente",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="category",
            field=mptt.fields.TreeForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ads",
                to="ads.category",
                verbose_name="Catégorie",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="ads.ad",
                verbose_name="Annonce",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddConstraint(
            model_name="adimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("ad",),
                name="unique_primary_image_per_ad",
            ),
        ),
        migrations.AddIndex(
            model_name="adview",
            index=models.Index(
                fields=["ad", "viewed_at"], name="ads_adview_ad_id_519a73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adview",
            index=models.Index(
                fields=["session_key", "ad"], name="ads_adview_session_09c76a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adview",
            index=models.Index(
                fields=["user", "viewed_at"], name="ads_adview_user_id_7d23e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["slug", "is_active"], name="ads_categor_slug_9fdcd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["parent", "is_active"], name="ads_categor_parent__1c7a6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["tree_id", "lft"], name="ads_category_tree_id_lft_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                fields=["status", "created_at"], name="ads_ad_status_f0db0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                fields=["seller", "status"], name="ads_ad_seller__10008f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                fields=["country_from", "country_to"], name="ads_ad_country_eb4a3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                fields=["price", "status"], name="ads_ad_price_c094b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                fields=["category", "status"], name="ads_ad_categor_cf5a94_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "ad")},
        ),
    ]
