# Generated by Django 6.0 on 2026-01-15 08:34

import colis.models
import django.core.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PackageStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistiques",
                "verbose_name_plural": "Statistiques",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Titre du colis"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Décrivez votre colis en détail",
                        verbose_name="Description détaillée",
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("SMALL_PACKAGE", "Petit colis (< 30kg)"),
                            ("MEDIUM_PACKAGE", "Colis moyen (30-100kg)"),
                            ("LARGE_PACKAGE", "Gros colis (100-500kg)"),
                            ("FURNITURE", "Meuble"),
                            ("PALLET", "Palette"),
                            ("VEHICLE_PART", "Pièce auto"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de colis",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Poids en kilogrammes",
                        max_digits=8,
                        verbose_name="Poids (kg)",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Longueur (cm)"
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Largeur (cm)"
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Hauteur (cm)"
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        editable=False,
                        max_digits=10,
                        null=True,
                        verbose_name="Volume (L)",
                    ),
                ),
                (
                    "pickup_country",
                    django_countries.fields.CountryField(
                        help_text="Pays où se trouve le colis",
                        max_length=2,
                        verbose_name="Pays de départ",
                    ),
                ),
                (
                    "pickup_city",
                    models.CharField(max_length=100, verbose_name="Ville de départ"),
                ),
                (
                    "pickup_address",
                    models.TextField(blank=True, verbose_name="Adresse de départ"),
                ),
                (
                    "pickup_postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Code postal départ"
                    ),
                ),
                (
                    "pickup_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude départ",
                    ),
                ),
                (
                    "pickup_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude départ",
                    ),
                ),
                (
                    "delivery_country",
                    django_countries.fields.CountryField(
                        help_text="Pays où le colis doit être livré",
                        max_length=2,
                        verbose_name="Pays de destination",
                    ),
                ),
                (
                    "delivery_city",
                    models.CharField(
                        max_length=100, verbose_name="Ville de destination"
                    ),
                ),
                (
                    "delivery_address",
                    models.TextField(blank=True, verbose_name="Adresse de destination"),
                ),
                (
                    "delivery_postal_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Code postal destination",
                    ),
                ),
                (
                    "delivery_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude destination",
                    ),
                ),
                (
                    "delivery_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude destination",
                    ),
                ),
                (
                    "pickup_date",
                    models.DateField(
                        help_text="Date à laquelle le colis est disponible",
                        verbose_name="Date de départ souhaitée",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        help_text="Date limite de livraison",
                        verbose_name="Date de livraison souhaitée",
                    ),
                ),
                (
                    "flexible_dates",
                    models.BooleanField(
                        default=False,
                        help_text="Accepte des dates différentes de celles demandées",
                        verbose_name="Dates flexibles",
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Prix fixe"),
                            ("NEGOTIABLE", "Prix négociable"),
                            ("AUCTION", "Mise aux enchères"),
                        ],
                        default="NEGOTIABLE",
                        max_length=20,
                        verbose_name="Type de prix",
                    ),
                ),
                (
                    "asking_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix en devise de départ",
                        max_digits=10,
                        verbose_name="Prix demandé",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "€"),
                            ("USD", "$"),
                            ("GBP", "£"),
                            ("MAD", "DH"),
                            ("XOF", "CFA"),
                        ],
                        default="EUR",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "estimated_distance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Distance estimée (km)",
                    ),
                ),
                (
                    "is_fragile",
                    models.BooleanField(default=False, verbose_name="Fragile"),
                ),
                (
                    "requires_insurance",
                    models.BooleanField(
                        default=False, verbose_name="Requiert assurance"
                    ),
                ),
                (
                    "insurance_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valeur à assurer",
                    ),
                ),
                (
                    "requires_packaging",
                    models.BooleanField(
                        default=False, verbose_name="Requiert emballage"
                    ),
                ),
                (
                    "requires_loading_help",
                    models.BooleanField(
                        default=False, verbose_name="Requiert aide au chargement"
                    ),
                ),
                (
                    "requires_unloading_help",
                    models.BooleanField(
                        default=False, verbose_name="Requiert aide au déchargement"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("AVAILABLE", "Disponible"),
                            ("RESERVED", "Réservé"),
                            ("IN_TRANSIT", "En transit"),
                            ("DELIVERED", "Livré"),
                            ("CANCELLED", "Annulé"),
                            ("EXPIRED", "Expiré"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Colis en vedette"),
                ),
                (
                    "featured_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="En vedette jusqu'au"
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Mots-clés SEO"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="Description SEO"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Nombre de vues"
                    ),
                ),
                (
                    "offer_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Nombre d'offres"
                    ),
                ),
                (
                    "favorite_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Nombre de favoris"
                    ),
                ),
                (
                    "free_images_allowed",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Nombre de photos gratuites"
                    ),
                ),
                (
                    "paid_images_used",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Photos payantes utilisées"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("reserved_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Colis",
                "verbose_name_plural": "Colis",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_feature_package", "Peut mettre en vedette un colis"),
                    ("can_moderate_package", "Peut modérer les colis"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PackageCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=200,
                        verbose_name="Nom de la catégorie",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Version URL-friendly du nom",
                        max_length=200,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée de la catégorie",
                        verbose_name="Description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Exemple: fa-box, fa-couch, fa-tshirt",
                        max_length=100,
                        verbose_name="Icône FontAwesome",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="colis/categories/",
                        verbose_name="Image de la catégorie",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Désactiver pour cacher la catégorie",
                        verbose_name="Active",
                    ),
                ),
                (
                    "show_in_menu",
                    models.BooleanField(
                        default=True, verbose_name="Afficher dans le menu"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Plus le nombre est bas, plus c'est prioritaire",
                        verbose_name="Ordre d'affichage",
                    ),
                ),
                (
                    "requires_dimensions",
                    models.BooleanField(
                        default=True,
                        help_text="Les colis de cette catégorie doivent avoir des dimensions",
                        verbose_name="Requiert dimensions",
                    ),
                ),
                (
                    "requires_weight",
                    models.BooleanField(
                        default=True,
                        help_text="Les colis de cette catégorie doivent avoir un poids",
                        verbose_name="Requiert poids",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Titre SEO"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="Description SEO"),
                ),
                (
                    "package_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Nombre de colis"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
            ],
            options={
                "verbose_name": "Catégorie de colis",
                "verbose_name_plural": "Catégories de colis",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PackageFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Colis favori",
                "verbose_name_plural": "Colis favoris",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PackageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=colis.models.package_image_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp"]
                            ),
                            colis.models.validate_file_size,
                        ],
                        verbose_name="Image",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="colis/thumbnails/",
                        verbose_name="Miniature",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Légende"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Image principale"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Image de colis",
                "verbose_name_plural": "Images de colis",
                "ordering": ["is_primary", "display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PackageReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("SPAM", "Spam ou publicité"),
                            ("FRAUD", "Fraude ou arnaque"),
                            ("INAPPROPRIATE", "Contenu inapproprié"),
                            ("WRONG_CATEGORY", "Mauvaise catégorie"),
                            ("PROHIBITED", "Article prohibé"),
                            ("DUPLICATE", "Colis en double"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Raison du signalement",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description détaillée"),
                ),
                (
                    "evidence",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="colis/reports/",
                        verbose_name="Preuve",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("IN_REVIEW", "En revue"),
                            ("RESOLVED", "Résolu"),
                            ("DISMISSED", "Rejeté"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, verbose_name="Notes de l'administrateur"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Résolu le"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Signalement de colis",
                "verbose_name_plural": "Signalements de colis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PackageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True, max_length=40, verbose_name="Clé de session"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("referer", models.URLField(blank=True, verbose_name="Referer")),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Vue de colis",
                "verbose_name_plural": "Vues de colis",
            },
        ),
        migrations.CreateModel(
            name="TransportOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix proposé"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "€"),
                            ("USD", "$"),
                            ("GBP", "£"),
                            ("MAD", "DH"),
                            ("XOF", "CFA"),
                        ],
                        default="EUR",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "proposed_pickup_date",
                    models.DateField(verbose_name="Date de départ proposée"),
                ),
                (
                    "proposed_delivery_date",
                    models.DateField(verbose_name="Date de livraison proposée"),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Expliquez pourquoi vous êtes le bon transporteur",
                        verbose_name="Message au vendeur",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("ACCEPTED", "Acceptée"),
                            ("REJECTED", "Rejetée"),
                            ("CANCELLED", "Annulée"),
                            ("EXPIRED", "Expirée"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "provides_insurance",
                    models.BooleanField(
                        default=False, verbose_name="Fournit assurance"
                    ),
                ),
                (
                    "insurance_coverage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Couverture d'assurance",
                    ),
                ),
                (
                    "provides_packaging",
                    models.BooleanField(
                        default=False, verbose_name="Fournit emballage"
                    ),
                ),
                (
                    "provides_loading",
                    models.BooleanField(
                        default=False, verbose_name="Fournit chargement"
                    ),
                ),
                (
                    "provides_unloading",
                    models.BooleanField(
                        default=False, verbose_name="Fournit déchargement"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Raison du refus"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Accepté le"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Date d'expiration de l'offre",
                        verbose_name="Expire le",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Offre de transport",
                "verbose_name_plural": "Offres de transport",
                "ordering": ["-created_at"],
            },
        ),
    ]
