# Generated by Django 6.0 on 2025-12-31 08:04

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carriers", "0002_initial"),
        ("colis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_packages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Expéditeur",
            ),
        ),
        migrations.AddField(
            model_name="packagecategory",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="Sélectionnez une catégorie parente si applicable",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="colis.packagecategory",
                verbose_name="Catégorie parente",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="category",
            field=mptt.fields.TreeForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packages",
                to="colis.packagecategory",
                verbose_name="Catégorie",
            ),
        ),
        migrations.AddField(
            model_name="packagefavorite",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="colis.package",
                verbose_name="Colis",
            ),
        ),
        migrations.AddField(
            model_name="packagefavorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="package_favorites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="packageimage",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="colis.package",
                verbose_name="Colis",
            ),
        ),
        migrations.AddField(
            model_name="packagereport",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="colis.package",
                verbose_name="Colis",
            ),
        ),
        migrations.AddField(
            model_name="packagereport",
            name="reporter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="package_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Signaleur",
            ),
        ),
        migrations.AddField(
            model_name="packagereport",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_package_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Résolu par",
            ),
        ),
        migrations.AddField(
            model_name="packageview",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views_tracking",
                to="colis.package",
                verbose_name="Colis",
            ),
        ),
        migrations.AddField(
            model_name="packageview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="package_views",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="transportoffer",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transport_offers",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="transportoffer",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transport_offers",
                to="colis.package",
                verbose_name="Colis",
            ),
        ),
        migrations.AddIndex(
            model_name="packagecategory",
            index=models.Index(
                fields=["slug", "is_active"], name="colis_packa_slug_606730_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="packagecategory",
            index=models.Index(
                fields=["parent", "is_active"], name="colis_packa_parent__f4d408_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="packagecategory",
            index=models.Index(
                fields=["tree_id", "lft"], name="colis_packagecategory_treef25a"
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["status", "created_at"], name="colis_packa_status_6b831c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["sender", "status"], name="colis_packa_sender__0df8ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["pickup_country", "delivery_country"],
                name="colis_packa_pickup__0f1de9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["pickup_date", "delivery_date"],
                name="colis_packa_pickup__5ccd61_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["package_type", "status"], name="colis_packa_package_18febe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["asking_price", "status"], name="colis_packa_asking__314189_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="packagefavorite",
            unique_together={("user", "package")},
        ),
        migrations.AddConstraint(
            model_name="packageimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("package",),
                name="unique_primary_image_per_package",
            ),
        ),
        migrations.AddIndex(
            model_name="packageview",
            index=models.Index(
                fields=["package", "viewed_at"], name="colis_packa_package_17fa2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="packageview",
            index=models.Index(
                fields=["session_key", "package"], name="colis_packa_session_2431f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="packageview",
            index=models.Index(
                fields=["user", "viewed_at"], name="colis_packa_user_id_60ad9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transportoffer",
            index=models.Index(
                fields=["package", "status"], name="colis_trans_package_727735_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transportoffer",
            index=models.Index(
                fields=["carrier", "status"], name="colis_trans_carrier_487e10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transportoffer",
            index=models.Index(
                fields=["status", "expires_at"], name="colis_trans_status_3a1514_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transportoffer",
            unique_together={("package", "carrier")},
        ),
    ]
