# Generated by Django 6.0 on 2025-12-31 08:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=200, verbose_name="Raison"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Utilisateur bloqué",
                "verbose_name_plural": "Utilisateurs bloqués",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "conversation_type",
                    models.CharField(
                        choices=[
                            ("PRIVATE", "Privé"),
                            ("GROUP", "Groupe"),
                            ("AD_RELATED", "Lié à une annonce"),
                            ("CARRIER_RELATED", "Lié à un transporteur"),
                            ("SUPPORT", "Support"),
                        ],
                        default="PRIVATE",
                        max_length=20,
                        verbose_name="Type de conversation",
                    ),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=200, verbose_name="Sujet"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="Archivée"),
                ),
                (
                    "is_blocked",
                    models.BooleanField(default=False, verbose_name="Bloquée"),
                ),
                (
                    "blocked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bloquée le"
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernier message le"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Archive de conversation",
                "verbose_name_plural": "Archives de conversations",
                "ordering": ["-archived_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Contenu du message", verbose_name="Contenu"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lu le"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="messaging/attachments/%Y/%m/%d/",
                        verbose_name="Pièce jointe",
                    ),
                ),
                (
                    "attachment_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nom du fichier"
                    ),
                ),
                (
                    "attachment_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Taille du fichier (octets)"
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["sent_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("SPAM", "Spam"),
                            ("HARASSMENT", "Harcèlement"),
                            ("INAPPROPRIATE", "Contenu inapproprié"),
                            ("SCAM", "Arnaque"),
                            ("THREAT", "Menace"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Raison",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "evidence",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="messaging/reports/%Y/%m/%d/",
                        verbose_name="Preuve",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("UNDER_REVIEW", "En examen"),
                            ("RESOLVED", "Résolu"),
                            ("DISMISSED", "Rejeté"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, verbose_name="Notes de l'administrateur"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Résolu le"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Signalement de message",
                "verbose_name_plural": "Signalements de messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("MESSAGE_RECEIVED", "Message reçu"),
                            ("MESSAGE_READ", "Message lu"),
                            ("CONVERSATION_NEW", "Nouvelle conversation"),
                            ("CONVERSATION_ARCHIVED", "Conversation archivée"),
                            ("SYSTEM", "Système"),
                            ("AD_RELATED", "Lié à une annonce"),
                            ("CARRIER_RELATED", "Lié à un transporteur"),
                            ("PAYMENT", "Paiement"),
                            ("SECURITY", "Sécurité"),
                        ],
                        max_length=30,
                        verbose_name="Type de notification",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                ("is_read", models.BooleanField(default=False, verbose_name="Lue")),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="Importante"),
                ),
                (
                    "action_url",
                    models.URLField(blank=True, verbose_name="URL d'action"),
                ),
                (
                    "action_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Texte de l'action"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expire le"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserMessageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Notifications par email"
                    ),
                ),
                (
                    "push_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Notifications push"
                    ),
                ),
                (
                    "desktop_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Notifications bureau"
                    ),
                ),
                (
                    "allow_messages_from",
                    models.CharField(
                        choices=[
                            ("EVERYONE", "Tout le monde"),
                            ("CONTACTS", "Contacts uniquement"),
                            ("NOBODY", "Personne"),
                        ],
                        default="EVERYONE",
                        max_length=20,
                        verbose_name="Autoriser les messages de",
                    ),
                ),
                (
                    "auto_archive_conversations",
                    models.BooleanField(
                        default=False,
                        verbose_name="Archiver automatiquement les conversations",
                    ),
                ),
                (
                    "archive_after_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Archiver après (jours)"
                    ),
                ),
                (
                    "auto_delete_messages",
                    models.BooleanField(
                        default=False,
                        verbose_name="Supprimer automatiquement les messages",
                    ),
                ),
                (
                    "delete_after_days",
                    models.PositiveIntegerField(
                        default=365, verbose_name="Supprimer après (jours)"
                    ),
                ),
                (
                    "show_online_status",
                    models.BooleanField(
                        default=True, verbose_name="Afficher le statut en ligne"
                    ),
                ),
                (
                    "show_read_receipts",
                    models.BooleanField(
                        default=True, verbose_name="Afficher les accusés de lecture"
                    ),
                ),
                (
                    "block_spam_messages",
                    models.BooleanField(
                        default=True, verbose_name="Bloquer les messages indésirables"
                    ),
                ),
                (
                    "filter_profanity",
                    models.BooleanField(
                        default=True, verbose_name="Filtrer les gros mots"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paramètres de messagerie",
                "verbose_name_plural": "Paramètres de messagerie",
            },
        ),
    ]
