# Generated by Django 6.0 on 2026-01-15 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ads", "0002_initial"),
        ("carriers", "0002_initial"),
        ("messaging", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="blockeduser",
            name="blocked",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Bloqué",
            ),
        ),
        migrations.AddField(
            model_name="blockeduser",
            name="blocker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Bloqueur",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="blocked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocked_conversations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Bloquée par",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="participants",
            field=models.ManyToManyField(
                related_name="conversations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Participants",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="related_ad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="ads.ad",
                verbose_name="Annonce liée",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="related_carrier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="carriers.carrier",
                verbose_name="Transporteur lié",
            ),
        ),
        migrations.AddField(
            model_name="conversationarchive",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archives",
                to="messaging.conversation",
                verbose_name="Conversation",
            ),
        ),
        migrations.AddField(
            model_name="conversationarchive",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archived_conversations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="messaging.conversation",
                verbose_name="Conversation",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Supprimé par",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="messaging.message",
                verbose_name="Message parent",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Destinataire",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Expéditeur",
            ),
        ),
        migrations.AddField(
            model_name="messagereport",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="messaging.message",
                verbose_name="Message",
            ),
        ),
        migrations.AddField(
            model_name="messagereport",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Signaleur",
            ),
        ),
        migrations.AddField(
            model_name="messagereport",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_message_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Résolu par",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_ad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="ads.ad",
                verbose_name="Annonce liée",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="messaging.conversation",
                verbose_name="Conversation liée",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="messaging.message",
                verbose_name="Message lié",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="usermessagesettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_settings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blockeduser",
            unique_together={("blocker", "blocked")},
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["uuid"], name="messaging_c_uuid_521233_idx"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["conversation_type", "is_active"],
                name="messaging_c_convers_6a9ad5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["last_message_at"], name="messaging_c_last_me_87f299_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conversationarchive",
            unique_together={("user", "conversation")},
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["uuid"], name="messaging_m_uuid_9bbd15_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "sent_at"],
                name="messaging_m_convers_118d4c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "sent_at"], name="messaging_m_sender__0f8c6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["recipient", "is_read", "sent_at"],
                name="messaging_m_recipie_749da0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["is_deleted", "sent_at"], name="messaging_m_is_dele_1387ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "created_at"],
                name="messaging_n_user_id_1f2092_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type", "created_at"],
                name="messaging_n_notific_d000e1_idx",
            ),
        ),
    ]
