# Generated by Django 6.0 on 2026-01-15 08:34

import django.contrib.gis.db.models.fields
import django.core.validators
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active_in_frontend",
                    models.BooleanField(
                        default=False,
                        help_text="Si activé, le transporteur apparaît dans les recherches frontend",
                        verbose_name="Actif dans le frontend",
                    ),
                ),
                (
                    "carrier_type",
                    models.CharField(
                        choices=[
                            ("CARRIER", "Transporteur Professionnel"),
                            ("CARRIER_PERSONAL", "Transporteur Particulier"),
                        ],
                        help_text="Note: doit correspondre au rôle dans le profil utilisateur",
                        max_length=20,
                        verbose_name="Type de transporteur",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("APPROVED", "Approuvé"),
                            ("REJECTED", "Rejeté"),
                            ("SUSPENDED", "Suspendu"),
                            ("INACTIVE", "Inactif"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut de transporteur",
                    ),
                ),
                (
                    "verification_level",
                    models.IntegerField(
                        default=0,
                        help_text="De 0 (non vérifié) à 5 (entièrement vérifié) - spécifique au transport",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Niveau de vérification transporteur",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Vérifié le (transport)"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, verbose_name="Raison du rejet (transport)"
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Photo spécifique pour le profil transporteur",
                        null=True,
                        upload_to="carriers/profile_photos/%Y/%m/%d/",
                        verbose_name="Photo de profil transporteur",
                    ),
                ),
                (
                    "id_front",
                    models.ImageField(
                        blank=True,
                        help_text="Pour vérification spécifique transport",
                        null=True,
                        upload_to="carriers/ids/%Y/%m/%d/",
                        verbose_name="Recto pièce d'identité (transport)",
                    ),
                ),
                (
                    "id_back",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="carriers/ids/%Y/%m/%d/",
                        verbose_name="Verso pièce d'identité (transport)",
                    ),
                ),
                (
                    "transport_company_name",
                    models.CharField(
                        blank=True,
                        help_text="Spécifique à l'activité de transport",
                        max_length=200,
                        verbose_name="Nom de l'entreprise de transport",
                    ),
                ),
                (
                    "transport_company_registration",
                    models.CharField(
                        blank=True,
                        help_text="Spécifique à l'activité de transport",
                        max_length=100,
                        verbose_name="Numéro d'immatriculation transport",
                    ),
                ),
                (
                    "transport_tax_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Numéro fiscal transport",
                    ),
                ),
                (
                    "transport_company_address",
                    models.TextField(
                        blank=True,
                        help_text="Adresse spécifique pour l'activité de transport",
                        verbose_name="Adresse de l'entreprise de transport",
                    ),
                ),
                (
                    "vehicle_registration_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="carriers/documents/vehicle_registration/",
                        verbose_name="Certificat d'immatriculation véhicule",
                    ),
                ),
                (
                    "transport_insurance_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="carriers/documents/transport_insurance/",
                        verbose_name="Certificat d'assurance transport",
                    ),
                ),
                (
                    "transport_operator_license",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="carriers/documents/transport_license/",
                        verbose_name="Licence d'exploitation transport",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("CAR", "Voiture"),
                            ("VAN", "Camionnette"),
                            ("TRUCK_SMALL", "Camion (3.5T)"),
                            ("TRUCK_MEDIUM", "Camion (7.5T)"),
                            ("TRUCK_LARGE", "Camion (19T+)"),
                            ("MOTORCYCLE", "Moto"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de véhicule",
                    ),
                ),
                (
                    "vehicle_make",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Marque du véhicule"
                    ),
                ),
                (
                    "vehicle_model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Modèle du véhicule"
                    ),
                ),
                (
                    "vehicle_year",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1990),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Année du véhicule",
                    ),
                ),
                (
                    "vehicle_registration",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Plaque d'immatriculation",
                    ),
                ),
                (
                    "vehicle_photo_front",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="carriers/vehicles/%Y/%m/%d/",
                        verbose_name="Photo avant du véhicule",
                    ),
                ),
                (
                    "vehicle_photo_back",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="carriers/vehicles/%Y/%m/%d/",
                        verbose_name="Photo arrière du véhicule",
                    ),
                ),
                (
                    "vehicle_photo_side",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="carriers/vehicles/%Y/%m/%d/",
                        verbose_name="Photo côté du véhicule",
                    ),
                ),
                (
                    "max_weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=100,
                        help_text="Charge utile maximale",
                        max_digits=8,
                        verbose_name="Poids maximum (kg)",
                    ),
                ),
                (
                    "max_volume",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        help_text="Volume utile maximum",
                        max_digits=10,
                        verbose_name="Volume maximum (m³)",
                    ),
                ),
                (
                    "max_length",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        max_digits=6,
                        verbose_name="Longueur maximum (m)",
                    ),
                ),
                (
                    "max_width",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=6,
                        verbose_name="Largeur maximum (m)",
                    ),
                ),
                (
                    "max_height",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=6,
                        verbose_name="Hauteur maximum (m)",
                    ),
                ),
                (
                    "coverage_countries",
                    django_countries.fields.CountryField(
                        blank=True,
                        max_length=746,
                        multiple=True,
                        verbose_name="Pays de couverture transport",
                    ),
                ),
                (
                    "coverage_cities",
                    models.TextField(
                        blank=True,
                        help_text="Villes spécifiques pour le transport, séparées par des virgules",
                        verbose_name="Villes de couverture (transport)",
                    ),
                ),
                (
                    "accepted_merchandise_types",
                    models.JSONField(
                        default=list,
                        help_text="Liste des types de marchandises acceptées pour le transport",
                        verbose_name="Types de marchandises acceptées",
                    ),
                ),
                (
                    "custom_merchandise_types",
                    models.TextField(
                        blank=True,
                        help_text="Saisissez vos types personnalisés séparés par des virgules",
                        verbose_name="Types de marchandises personnalisés",
                    ),
                ),
                (
                    "transport_weekly_schedule",
                    models.JSONField(
                        default=dict,
                        help_text="Disponibilités spécifiques pour le transport",
                        verbose_name="Emploi du temps hebdomadaire transport",
                    ),
                ),
                (
                    "transport_available_from",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Disponible à partir du (transport)",
                    ),
                ),
                (
                    "transport_available_until",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Disponible jusqu'au (transport)",
                    ),
                ),
                (
                    "provides_packaging",
                    models.BooleanField(
                        default=False, verbose_name="Fournit l'emballage"
                    ),
                ),
                (
                    "provides_insurance",
                    models.BooleanField(
                        default=False, verbose_name="Fournit l'assurance transport"
                    ),
                ),
                (
                    "provides_loading",
                    models.BooleanField(
                        default=False, verbose_name="Fournit le chargement"
                    ),
                ),
                (
                    "provides_unloading",
                    models.BooleanField(
                        default=False, verbose_name="Fournit le déchargement"
                    ),
                ),
                (
                    "base_price_per_km",
                    models.DecimalField(
                        decimal_places=4,
                        default=1.0,
                        max_digits=8,
                        verbose_name="Prix de base par km (€)",
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        max_digits=8,
                        verbose_name="Prix minimum (€)",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "€"),
                            ("USD", "$"),
                            ("GBP", "£"),
                            ("MAD", "DH"),
                            ("XOF", "CFA"),
                        ],
                        default="EUR",
                        max_length=3,
                        verbose_name="Devise pour le transport",
                    ),
                ),
                (
                    "transport_is_available",
                    models.BooleanField(
                        default=True,
                        verbose_name="Disponible pour des missions de transport",
                    ),
                ),
                (
                    "total_transport_missions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total des missions de transport"
                    ),
                ),
                (
                    "completed_transport_missions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Missions de transport complétées"
                    ),
                ),
                (
                    "transport_success_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Taux de réussite transport (%)",
                    ),
                ),
                (
                    "transport_average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Note moyenne transport",
                    ),
                ),
                (
                    "transport_total_reviews",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre total d'avis transport"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Profil Transporteur",
                "verbose_name_plural": "Profils Transporteurs",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_verify_carrier", "Peut vérifier les transporteurs"),
                    ("can_approve_carrier", "Peut approuver les transporteurs"),
                    (
                        "can_view_carrier_stats",
                        "Peut voir les statistiques des transporteurs",
                    ),
                    (
                        "can_activate_carrier_frontend",
                        "Peut activer/désactiver dans le frontend",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CarrierAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(verbose_name="Début de disponibilité"),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(verbose_name="Fin de disponibilité"),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="Localisation"
                    ),
                ),
                (
                    "available_weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=8,
                        verbose_name="Poids disponible (kg)",
                    ),
                ),
                (
                    "available_volume",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="Volume disponible (m³)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "is_booked",
                    models.BooleanField(default=False, verbose_name="Réservé"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Disponibilité de transporteur",
                "verbose_name_plural": "Disponibilités de transporteurs",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="CarrierDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("ID_CARD", "Carte d'identité"),
                            ("PASSPORT", "Passeport"),
                            ("DRIVER_LICENSE", "Permis de conduire"),
                            ("VEHICLE_REGISTRATION", "Carte grise"),
                            ("INSURANCE", "Assurance"),
                            ("COMPANY_REGISTRATION", "Immatriculation société"),
                            ("TAX_CERTIFICATE", "Certificat fiscal"),
                            ("CUSTOMS_DOCUMENT", "Document douanier"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=30,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "is_customs_document",
                    models.BooleanField(
                        default=False, verbose_name="Document douanier"
                    ),
                ),
                (
                    "customs_country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, verbose_name="Pays concerné"
                    ),
                ),
                (
                    "customs_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Type de document douanier",
                    ),
                ),
                (
                    "declaration_data",
                    models.JSONField(
                        default=dict,
                        help_text="Données pour le générateur de formulaires",
                        verbose_name="Données de déclaration",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="carriers/documents/%Y/%m/%d/", verbose_name="Fichier"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="carriers/documents/thumbnails/%Y/%m/%d/",
                        verbose_name="Miniature",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Description"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Vérifié"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Vérifié le"
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(blank=True, verbose_name="Notes de vérification"),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(default=False, verbose_name="Rappel envoyé"),
                ),
                (
                    "reminder_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de rappel"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Document de transporteur",
                "verbose_name_plural": "Documents de transporteurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarrierNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("NEW_MISSION", "Nouvelle mission"),
                            ("MISSION_UPDATE", "Mise à jour de mission"),
                            ("PAYMENT_RECEIVED", "Paiement reçu"),
                            ("REVIEW_RECEIVED", "Avis reçu"),
                            ("DOCUMENT_VERIFIED", "Document vérifié"),
                            ("STATUS_CHANGED", "Statut changé"),
                            ("SYSTEM", "Système"),
                            ("COLLECTION_DAY", "Jour de collecte"),
                            ("EXPENSE_ALERT", "Alerte dépense"),
                            ("DOCUMENT_EXPIRY", "Document expiré"),
                            ("ROUTE_OPTIMIZED", "Itinéraire optimisé"),
                            ("NEW_OFFER", "Nouvelle offre"),
                        ],
                        max_length=30,
                        verbose_name="Type de notification",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "related_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID objet lié"
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Type d'objet lié"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="Important"),
                ),
                (
                    "action_url",
                    models.URLField(blank=True, verbose_name="URL d'action"),
                ),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("WARNING", "Avertissement"),
                            ("URGENT", "Urgent"),
                        ],
                        default="INFO",
                        max_length=20,
                        verbose_name="Niveau d'alerte",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Notification de transporteur",
                "verbose_name_plural": "Notifications de transporteurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarrierOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre de l'offre"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("IMMEDIATE", "Immédiate"),
                            ("SCHEDULED", "Planifiée"),
                            ("RECURRING", "Récurrente"),
                            ("GROUPED", "Groupée"),
                        ],
                        default="IMMEDIATE",
                        max_length=20,
                        verbose_name="Type d'offre",
                    ),
                ),
                (
                    "start_country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Pays de départ"
                    ),
                ),
                (
                    "start_city",
                    models.CharField(max_length=100, verbose_name="Ville de départ"),
                ),
                (
                    "end_country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Pays d'arrivée"
                    ),
                ),
                (
                    "end_city",
                    models.CharField(max_length=100, verbose_name="Ville d'arrivée"),
                ),
                (
                    "available_from",
                    models.DateTimeField(verbose_name="Disponible à partir du"),
                ),
                (
                    "available_until",
                    models.DateTimeField(verbose_name="Disponible jusqu'au"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "€"),
                            ("USD", "$"),
                            ("GBP", "£"),
                            ("MAD", "DH"),
                            ("XOF", "CFA"),
                        ],
                        default="EUR",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "available_weight",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=8,
                        verbose_name="Poids disponible (kg)",
                    ),
                ),
                (
                    "available_volume",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="Volume disponible (m³)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_booked",
                    models.BooleanField(default=False, verbose_name="Réservée"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de vues"
                    ),
                ),
                (
                    "inquiries_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de demandes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Offre de transporteur",
                "verbose_name_plural": "Offres de transporteurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarrierReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Note (1-5)",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("comment", models.TextField(verbose_name="Commentaire")),
                (
                    "communication",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Communication",
                    ),
                ),
                (
                    "punctuality",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Ponctualité",
                    ),
                ),
                (
                    "handling",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Manutention",
                    ),
                ),
                (
                    "professionalism",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Professionalisme",
                    ),
                ),
                (
                    "recommended",
                    models.BooleanField(default=False, verbose_name="Recommandé"),
                ),
                (
                    "on_time",
                    models.BooleanField(default=False, verbose_name="À l'heure"),
                ),
                (
                    "careful",
                    models.BooleanField(default=False, verbose_name="Soigneux"),
                ),
                (
                    "good_communication",
                    models.BooleanField(
                        default=False, verbose_name="Bon communicateur"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Approuvé"),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Visible"),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, verbose_name="Notes de l'administrateur"
                    ),
                ),
                (
                    "carrier_response",
                    models.TextField(
                        blank=True, verbose_name="Réponse du transporteur"
                    ),
                ),
                (
                    "response_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de réponse"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Avis sur transporteur",
                "verbose_name_plural": "Avis sur transporteurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarrierRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Pays de départ"
                    ),
                ),
                (
                    "start_city",
                    models.CharField(max_length=100, verbose_name="Ville de départ"),
                ),
                (
                    "start_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="Coordonnées GPS du point de départ",
                        null=True,
                        srid=4326,
                        verbose_name="Localisation de départ",
                    ),
                ),
                (
                    "end_country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Pays d'arrivée"
                    ),
                ),
                (
                    "end_city",
                    models.CharField(max_length=100, verbose_name="Ville d'arrivée"),
                ),
                (
                    "end_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="Coordonnées GPS du point d'arrivée",
                        null=True,
                        srid=4326,
                        verbose_name="Localisation d'arrivée",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("ONE_TIME", "Ponctuel"),
                            ("WEEKLY", "Hebdomadaire"),
                            ("BIWEEKLY", "Bimensuel"),
                            ("MONTHLY", "Mensuel"),
                            ("REGULAR", "Régulier"),
                        ],
                        default="ONE_TIME",
                        max_length=20,
                        verbose_name="Fréquence",
                    ),
                ),
                ("departure_date", models.DateField(verbose_name="Date de départ")),
                ("arrival_date", models.DateField(verbose_name="Date d'arrivée")),
                (
                    "available_weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=8,
                        verbose_name="Poids disponible (kg)",
                    ),
                ),
                (
                    "available_volume",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="Volume disponible (m³)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("is_full", models.BooleanField(default=False, verbose_name="Complet")),
                (
                    "price_per_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="Prix par kg (€)",
                    ),
                ),
                (
                    "price_per_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="Prix par m³ (€)",
                    ),
                ),
                (
                    "fixed_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Prix fixe (€)",
                    ),
                ),
                (
                    "toll_costs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Coûts de péages (€)",
                    ),
                ),
                (
                    "tax_costs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Coûts de taxes (€)",
                    ),
                ),
                (
                    "fuel_costs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Coûts de carburant (€)",
                    ),
                ),
                (
                    "estimated_transit_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Temps de transit estimé"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Route de transporteur",
                "verbose_name_plural": "Routes de transporteurs",
                "ordering": ["departure_date"],
            },
        ),
        migrations.CreateModel(
            name="CarrierSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nom de la recherche"
                    ),
                ),
                (
                    "search_criteria",
                    models.JSONField(
                        default=dict, verbose_name="Critères de recherche"
                    ),
                ),
                (
                    "alerts_enabled",
                    models.BooleanField(default=False, verbose_name="Alertes activées"),
                ),
                (
                    "alert_frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Quotidien"),
                            ("WEEKLY", "Hebdomadaire"),
                            ("IMMEDIATE", "Immédiat"),
                        ],
                        default="DAILY",
                        max_length=20,
                        verbose_name="Fréquence des alertes",
                    ),
                ),
                (
                    "last_alert_sent",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière alerte envoyée"
                    ),
                ),
                (
                    "last_results_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de résultats précédent"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Recherche de transporteur",
                "verbose_name_plural": "Recherches de transporteurs",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CarrierStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_success_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Taux de livraison réussie (%)",
                    ),
                ),
                (
                    "on_time_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Taux de ponctualité (%)",
                    ),
                ),
                (
                    "satisfaction_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Taux de satisfaction (%)",
                    ),
                ),
                (
                    "zone_rankings",
                    models.JSONField(
                        default=dict,
                        help_text="Format: {'zone': 'rank', ...}",
                        verbose_name="Classements par zone",
                    ),
                ),
                (
                    "monthly_stats",
                    models.JSONField(
                        default=dict,
                        help_text="Format: {'YYYY-MM': {'missions': X, 'revenue': Y}, ...}",
                        verbose_name="Statistiques mensuelles",
                    ),
                ),
                (
                    "total_distance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Distance totale parcourue (km)",
                    ),
                ),
                (
                    "total_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Heures totales de travail",
                    ),
                ),
                (
                    "avg_delivery_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Temps moyen de livraison"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Statistique de transporteur",
                "verbose_name_plural": "Statistiques de transporteurs",
            },
        ),
        migrations.CreateModel(
            name="CollectionDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date de collecte")),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                ("end_time", models.TimeField(verbose_name="Heure de fin")),
                (
                    "is_scheduled",
                    models.BooleanField(default=False, verbose_name="Planifié"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Terminé"),
                ),
                (
                    "planned_total_weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=8,
                        verbose_name="Poids total planifié (kg)",
                    ),
                ),
                (
                    "planned_total_volume",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="Volume total planifié (m³)",
                    ),
                ),
                (
                    "actual_total_weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=8,
                        verbose_name="Poids total réel (kg)",
                    ),
                ),
                (
                    "actual_total_volume",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="Volume total réel (m³)",
                    ),
                ),
                (
                    "collection_route",
                    models.JSONField(
                        default=list,
                        help_text="Liste ordonnée des adresses à collecter",
                        verbose_name="Itinéraire de collecte",
                    ),
                ),
                (
                    "optimized_route",
                    models.JSONField(
                        default=list,
                        help_text="Itinéraire optimisé pour la collecte",
                        verbose_name="Itinéraire optimisé",
                    ),
                ),
                (
                    "estimated_distance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Distance estimée (km)",
                    ),
                ),
                (
                    "estimated_duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Durée estimée"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Jour de collecte",
                "verbose_name_plural": "Jours de collecte",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Début de période")),
                ("period_end", models.DateField(verbose_name="Fin de période")),
                (
                    "total_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Total des dépenses",
                    ),
                ),
                (
                    "total_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Total des revenus",
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Bénéfice net",
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="carriers/expense_reports/%Y/%m/%d/",
                        verbose_name="Fichier rapport",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Approuvé"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approuvé le"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rapport de dépenses",
                "verbose_name_plural": "Rapports de dépenses",
                "ordering": ["-period_end"],
            },
        ),
        migrations.CreateModel(
            name="FinancialTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("PAYMENT", "Paiement"),
                            ("EXPENSE", "Dépense"),
                            ("REFUND", "Remboursement"),
                            ("COMMISSION", "Commission"),
                            ("BONUS", "Bonus"),
                        ],
                        max_length=20,
                        verbose_name="Type de transaction",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "€"),
                            ("USD", "$"),
                            ("GBP", "£"),
                            ("MAD", "DH"),
                            ("XOF", "CFA"),
                        ],
                        default="EUR",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CASH", "Espèces"),
                            ("BANK_TRANSFER", "Virement bancaire"),
                            ("CARD", "Carte bancaire"),
                            ("MOBILE_MONEY", "Mobile money"),
                            ("PAYPAY", "PayPal"),
                            ("STRIPE", "Stripe"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Méthode de paiement",
                    ),
                ),
                (
                    "is_prepaid",
                    models.BooleanField(default=False, verbose_name="Prépaiement"),
                ),
                (
                    "expense_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FUEL", "Carburant"),
                            ("TOLL", "Péages"),
                            ("MAINTENANCE", "Entretien"),
                            ("INSURANCE", "Assurance"),
                            ("PARKING", "Parking"),
                            ("MEALS", "Repas"),
                            ("ACCOMMODATION", "Hébergement"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie de dépense",
                    ),
                ),
                (
                    "expense_description",
                    models.TextField(
                        blank=True, verbose_name="Description de la dépense"
                    ),
                ),
                (
                    "expense_receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="carriers/expenses/%Y/%m/%d/",
                        verbose_name="Reçu de dépense",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro de reçu"
                    ),
                ),
                (
                    "receipt_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="carriers/receipts/%Y/%m/%d/",
                        verbose_name="Fichier reçu",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro de facture"
                    ),
                ),
                (
                    "invoice_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="carriers/invoices/%Y/%m/%d/",
                        verbose_name="Fichier facture",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de transaction",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=True, verbose_name="Terminé"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Transaction financière",
                "verbose_name_plural": "Transactions financières",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mission_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Numéro de mission"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("ACCEPTED", "Acceptée"),
                            ("COLLECTING", "En collecte"),
                            ("IN_TRANSIT", "En transit"),
                            ("DELIVERING", "En livraison"),
                            ("DELIVERED", "Livrée"),
                            ("CANCELLED", "Annulée"),
                            ("PROBLEM", "Problème"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Basse"),
                            ("MEDIUM", "Moyenne"),
                            ("HIGH", "Haute"),
                            ("URGENT", "Urgente"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "sender_address",
                    models.TextField(verbose_name="Adresse de l'expéditeur"),
                ),
                (
                    "sender_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Téléphone expéditeur"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        max_length=200, verbose_name="Nom du destinataire"
                    ),
                ),
                (
                    "recipient_address",
                    models.TextField(verbose_name="Adresse du destinataire"),
                ),
                (
                    "recipient_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        region=None,
                        verbose_name="Téléphone destinataire",
                    ),
                ),
                (
                    "merchandise_type",
                    models.CharField(max_length=50, verbose_name="Type de marchandise"),
                ),
                (
                    "custom_merchandise_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Type personnalisé"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=3, max_digits=8, verbose_name="Poids (kg)"
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Longueur (m)"
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Largeur (m)"
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Hauteur (m)"
                    ),
                ),
                (
                    "preferred_pickup_date",
                    models.DateField(verbose_name="Date de collecte préférée"),
                ),
                (
                    "preferred_delivery_date",
                    models.DateField(verbose_name="Date de livraison préférée"),
                ),
                (
                    "actual_pickup_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de collecte réelle"
                    ),
                ),
                (
                    "actual_delivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de livraison réelle"
                    ),
                ),
                (
                    "agreed_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix convenu (€)"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "€"),
                            ("USD", "$"),
                            ("GBP", "£"),
                            ("MAD", "DH"),
                            ("XOF", "CFA"),
                        ],
                        default="EUR",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "delivery_proof_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="missions/delivery_proofs/%Y/%m/%d/",
                        verbose_name="Photo preuve de livraison",
                    ),
                ),
                (
                    "recipient_signature",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="missions/signatures/%Y/%m/%d/",
                        verbose_name="Signature du destinataire",
                    ),
                ),
                (
                    "delivery_notes",
                    models.TextField(blank=True, verbose_name="Notes de livraison"),
                ),
                (
                    "has_incident",
                    models.BooleanField(default=False, verbose_name="A un incident"),
                ),
                (
                    "incident_description",
                    models.TextField(
                        blank=True, verbose_name="Description de l'incident"
                    ),
                ),
                (
                    "incident_resolved",
                    models.BooleanField(default=False, verbose_name="Incident résolu"),
                ),
                (
                    "delay_reason",
                    models.TextField(blank=True, verbose_name="Raison du retard"),
                ),
                (
                    "delay_duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Durée du retard"
                    ),
                ),
                (
                    "collection_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordre dans lequel collecter cet objet",
                        verbose_name="Ordre de collecte",
                    ),
                ),
                (
                    "position_in_vehicle",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Arrière gauche, dessus, etc.",
                        max_length=100,
                        verbose_name="Position dans le véhicule",
                    ),
                ),
                (
                    "is_fragile",
                    models.BooleanField(default=False, verbose_name="Fragile"),
                ),
                (
                    "requires_special_handling",
                    models.BooleanField(
                        default=False,
                        verbose_name="Nécessite une manipulation spéciale",
                    ),
                ),
                (
                    "current_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="Localisation actuelle",
                    ),
                ),
                (
                    "last_location_update",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Dernière mise à jour de localisation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Mission",
                "verbose_name_plural": "Missions",
                "ordering": ["-created_at"],
            },
        ),
    ]
