# Generated by Django 6.0 on 2025-12-31 08:04

import django.contrib.gis.db.models.fields
import django.core.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carrier_type",
                    models.CharField(
                        choices=[
                            ("PROFESSIONAL", "Professionnel"),
                            ("PERSONAL", "Particulier (Expatrié)"),
                        ],
                        max_length=20,
                        verbose_name="Type de transporteur",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("APPROVED", "Approuvé"),
                            ("REJECTED", "Rejeté"),
                            ("SUSPENDED", "Suspendu"),
                            ("INACTIVE", "Inactif"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "verification_level",
                    models.IntegerField(
                        default=0,
                        help_text="De 0 (non vérifié) à 5 (entièrement vérifié)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Niveau de vérification",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Vérifié le"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Raison du rejet"),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nom de l'entreprise"
                    ),
                ),
                (
                    "company_registration",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Numéro d'immatriculation",
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Numéro fiscal/TVA"
                    ),
                ),
                (
                    "company_address",
                    models.TextField(
                        blank=True, verbose_name="Adresse de l'entreprise"
                    ),
                ),
                (
                    "registration_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="carriers/documents/registration/",
                        verbose_name="Certificat d'immatriculation",
                    ),
                ),
                (
                    "insurance_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="carriers/documents/insurance/",
                        verbose_name="Certificat d'assurance",
                    ),
                ),
                (
                    "operator_license",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="carriers/documents/license/",
                        verbose_name="Licence d'exploitation",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("CAR", "Voiture"),
                            ("VAN", "Camionnette"),
                            ("TRUCK_SMALL", "Camion (3.5T)"),
                            ("TRUCK_MEDIUM", "Camion (7.5T)"),
                            ("TRUCK_LARGE", "Camion (19T+)"),
                            ("MOTORCYCLE", "Moto"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de véhicule",
                    ),
                ),
                (
                    "vehicle_make",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Marque du véhicule"
                    ),
                ),
                (
                    "vehicle_model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Modèle du véhicule"
                    ),
                ),
                (
                    "vehicle_year",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1990),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Année du véhicule",
                    ),
                ),
                (
                    "vehicle_registration",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Plaque d'immatriculation",
                    ),
                ),
                (
                    "max_weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=100,
                        help_text="Charge utile maximale",
                        max_digits=8,
                        verbose_name="Poids maximum (kg)",
                    ),
                ),
                (
                    "max_volume",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        help_text="Volume utile maximum",
                        max_digits=10,
                        verbose_name="Volume maximum (m³)",
                    ),
                ),
                (
                    "max_length",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        max_digits=6,
                        verbose_name="Longueur maximum (m)",
                    ),
                ),
                (
                    "max_width",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=6,
                        verbose_name="Largeur maximum (m)",
                    ),
                ),
                (
                    "max_height",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=6,
                        verbose_name="Hauteur maximum (m)",
                    ),
                ),
                (
                    "provides_packaging",
                    models.BooleanField(
                        default=False, verbose_name="Fournit l'emballage"
                    ),
                ),
                (
                    "provides_insurance",
                    models.BooleanField(
                        default=False, verbose_name="Fournit l'assurance"
                    ),
                ),
                (
                    "provides_loading",
                    models.BooleanField(
                        default=False, verbose_name="Fournit le chargement"
                    ),
                ),
                (
                    "provides_unloading",
                    models.BooleanField(
                        default=False, verbose_name="Fournit le déchargement"
                    ),
                ),
                (
                    "base_price_per_km",
                    models.DecimalField(
                        decimal_places=4,
                        default=1.0,
                        max_digits=8,
                        verbose_name="Prix de base par km (€)",
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        max_digits=8,
                        verbose_name="Prix minimum (€)",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "€"),
                            ("USD", "$"),
                            ("GBP", "£"),
                            ("MAD", "DH"),
                            ("XOF", "CFA"),
                        ],
                        default="EUR",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, verbose_name="Disponible pour des missions"
                    ),
                ),
                (
                    "available_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="Disponible à partir du"
                    ),
                ),
                (
                    "available_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Disponible jusqu'au"
                    ),
                ),
                (
                    "total_missions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total des missions"
                    ),
                ),
                (
                    "completed_missions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Missions complétées"
                    ),
                ),
                (
                    "success_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Taux de réussite (%)",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Note moyenne",
                    ),
                ),
                (
                    "total_reviews",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre total d'avis"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Transporteur",
                "verbose_name_plural": "Transporteurs",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_verify_carrier", "Peut vérifier les transporteurs"),
                    ("can_approve_carrier", "Peut approuver les transporteurs"),
                    (
                        "can_view_carrier_stats",
                        "Peut voir les statistiques des transporteurs",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CarrierAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(verbose_name="Début de disponibilité"),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(verbose_name="Fin de disponibilité"),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="Localisation"
                    ),
                ),
                (
                    "available_weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=8,
                        verbose_name="Poids disponible (kg)",
                    ),
                ),
                (
                    "available_volume",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="Volume disponible (m³)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "is_booked",
                    models.BooleanField(default=False, verbose_name="Réservé"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Disponibilité de transporteur",
                "verbose_name_plural": "Disponibilités de transporteurs",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="CarrierDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("ID_CARD", "Carte d'identité"),
                            ("PASSPORT", "Passeport"),
                            ("DRIVER_LICENSE", "Permis de conduire"),
                            ("VEHICLE_REGISTRATION", "Carte grise"),
                            ("INSURANCE", "Assurance"),
                            ("COMPANY_REGISTRATION", "Immatriculation société"),
                            ("TAX_CERTIFICATE", "Certificat fiscal"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=30,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="carriers/documents/%Y/%m/%d/", verbose_name="Fichier"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="carriers/documents/thumbnails/%Y/%m/%d/",
                        verbose_name="Miniature",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Description"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Vérifié"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Vérifié le"
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(blank=True, verbose_name="Notes de vérification"),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Document de transporteur",
                "verbose_name_plural": "Documents de transporteurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarrierNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("NEW_MISSION", "Nouvelle mission"),
                            ("MISSION_UPDATE", "Mise à jour de mission"),
                            ("PAYMENT_RECEIVED", "Paiement reçu"),
                            ("REVIEW_RECEIVED", "Avis reçu"),
                            ("DOCUMENT_VERIFIED", "Document vérifié"),
                            ("STATUS_CHANGED", "Statut changé"),
                            ("SYSTEM", "Système"),
                        ],
                        max_length=30,
                        verbose_name="Type de notification",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "related_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID objet lié"
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Type d'objet lié"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="Important"),
                ),
                (
                    "action_url",
                    models.URLField(blank=True, verbose_name="URL d'action"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Notification de transporteur",
                "verbose_name_plural": "Notifications de transporteurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarrierReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Note (1-5)",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("comment", models.TextField(verbose_name="Commentaire")),
                (
                    "communication",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Communication",
                    ),
                ),
                (
                    "punctuality",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Ponctualité",
                    ),
                ),
                (
                    "handling",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Manutention",
                    ),
                ),
                (
                    "professionalism",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Professionalisme",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Approuvé"),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Visible"),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, verbose_name="Notes de l'administrateur"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Avis sur transporteur",
                "verbose_name_plural": "Avis sur transporteurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarrierRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Pays de départ"
                    ),
                ),
                (
                    "start_city",
                    models.CharField(max_length=100, verbose_name="Ville de départ"),
                ),
                (
                    "start_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="Coordonnées GPS du point de départ",
                        null=True,
                        srid=4326,
                        verbose_name="Localisation de départ",
                    ),
                ),
                (
                    "end_country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Pays d'arrivée"
                    ),
                ),
                (
                    "end_city",
                    models.CharField(max_length=100, verbose_name="Ville d'arrivée"),
                ),
                (
                    "end_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="Coordonnées GPS du point d'arrivée",
                        null=True,
                        srid=4326,
                        verbose_name="Localisation d'arrivée",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("ONE_TIME", "Ponctuel"),
                            ("WEEKLY", "Hebdomadaire"),
                            ("BIWEEKLY", "Bimensuel"),
                            ("MONTHLY", "Mensuel"),
                            ("REGULAR", "Régulier"),
                        ],
                        default="ONE_TIME",
                        max_length=20,
                        verbose_name="Fréquence",
                    ),
                ),
                ("departure_date", models.DateField(verbose_name="Date de départ")),
                ("arrival_date", models.DateField(verbose_name="Date d'arrivée")),
                (
                    "available_weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=8,
                        verbose_name="Poids disponible (kg)",
                    ),
                ),
                (
                    "available_volume",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="Volume disponible (m³)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("is_full", models.BooleanField(default=False, verbose_name="Complet")),
                (
                    "price_per_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="Prix par kg (€)",
                    ),
                ),
                (
                    "price_per_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="Prix par m³ (€)",
                    ),
                ),
                (
                    "fixed_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Prix fixe (€)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Route de transporteur",
                "verbose_name_plural": "Routes de transporteurs",
                "ordering": ["departure_date"],
            },
        ),
    ]
