# Generated by Django 6.0 on 2026-01-15 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carriers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="carrier",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Administrateur qui a approuvé ce transporteur",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_carriers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approuvé par",
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="user",
            field=models.OneToOneField(
                help_text="L'utilisateur auquel est associé ce profil transporteur",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carrier_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="carrieravailability",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="carrierdocument",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="carrierdocument",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vérifié par",
            ),
        ),
        migrations.AddField(
            model_name="carriernotification",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="carrieroffer",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="carrierreview",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="carrierreview",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carrier_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auteur",
            ),
        ),
        migrations.AddField(
            model_name="carrierroute",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carrier_routes",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="carriersearch",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carrier_searches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="carrierstatistics",
            name="carrier",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statistics",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="collectionday",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_days",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="expensereport",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approuvé par",
            ),
        ),
        migrations.AddField(
            model_name="expensereport",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_reports",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="financialtransaction",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carrier_missions",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_missions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Expéditeur",
            ),
        ),
        migrations.AddField(
            model_name="financialtransaction",
            name="mission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="carriers.mission",
                verbose_name="Mission",
            ),
        ),
        migrations.AddIndex(
            model_name="carrier",
            index=models.Index(
                fields=["status", "carrier_type"], name="carriers_ca_status_7f3ecc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carrier",
            index=models.Index(
                fields=["transport_is_available", "status"],
                name="carriers_ca_transpo_dec1af_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carrier",
            index=models.Index(
                fields=["user", "status"], name="carriers_ca_user_id_484ac0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carrier",
            index=models.Index(
                fields=["coverage_countries"], name="carriers_ca_coverag_7869e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carrier",
            index=models.Index(
                fields=["is_active_in_frontend", "status", "transport_is_available"],
                name="carriers_ca_is_acti_60c18a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carrieravailability",
            index=models.Index(
                fields=["carrier", "start_datetime", "is_booked"],
                name="carriers_ca_carrier_9528db_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carriernotification",
            index=models.Index(
                fields=["carrier", "is_read", "created_at"],
                name="carriers_ca_carrier_83a765_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carriernotification",
            index=models.Index(
                fields=["notification_type", "created_at"],
                name="carriers_ca_notific_706257_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carrieroffer",
            index=models.Index(
                fields=["carrier", "is_active", "available_from"],
                name="carriers_ca_carrier_058c2f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carrieroffer",
            index=models.Index(
                fields=["start_country", "end_country", "is_active"],
                name="carriers_ca_start_c_f9f288_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carrieroffer",
            index=models.Index(
                fields=["offer_type", "is_active"],
                name="carriers_ca_offer_t_d2a038_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carrierreview",
            index=models.Index(
                fields=["carrier", "is_approved", "is_visible"],
                name="carriers_ca_carrier_ece7b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carrierreview",
            index=models.Index(
                fields=["reviewer", "created_at"], name="carriers_ca_reviewe_0792c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carrierreview",
            index=models.Index(
                fields=["rating", "created_at"], name="carriers_ca_rating_201e05_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="carrierreview",
            unique_together={("carrier", "reviewer")},
        ),
        migrations.AddIndex(
            model_name="carrierroute",
            index=models.Index(
                fields=["start_country", "end_country"],
                name="carriers_ca_start_c_24d42f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carrierroute",
            index=models.Index(
                fields=["departure_date", "is_active"],
                name="carriers_ca_departu_d158ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carrierroute",
            index=models.Index(
                fields=["carrier", "is_active"], name="carriers_ca_carrier_c67da6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carriersearch",
            index=models.Index(
                fields=["user", "alerts_enabled"], name="carriers_ca_user_id_6827de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collectionday",
            index=models.Index(
                fields=["carrier", "date", "is_completed"],
                name="carriers_co_carrier_2e7774_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collectionday",
            unique_together={("carrier", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="expensereport",
            unique_together={("carrier", "period_start", "period_end")},
        ),
        migrations.AddIndex(
            model_name="mission",
            index=models.Index(
                fields=["mission_number"], name="carriers_mi_mission_2516e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mission",
            index=models.Index(
                fields=["carrier", "status"], name="carriers_mi_carrier_feed52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mission",
            index=models.Index(
                fields=["sender", "status"], name="carriers_mi_sender__374693_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mission",
            index=models.Index(
                fields=["status", "preferred_pickup_date"],
                name="carriers_mi_status_5d53ce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mission",
            index=models.Index(
                fields=["collection_order"], name="carriers_mi_collect_c72a33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialtransaction",
            index=models.Index(
                fields=["carrier", "transaction_type", "transaction_date"],
                name="carriers_fi_carrier_d6db84_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialtransaction",
            index=models.Index(
                fields=["mission", "transaction_type"],
                name="carriers_fi_mission_28a778_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialtransaction",
            index=models.Index(
                fields=["transaction_date", "is_completed"],
                name="carriers_fi_transac_5678e3_idx",
            ),
        ),
    ]
