# Generated by Django 6.0 on 2025-12-31 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carriers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="carrier",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carrier_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="carrieravailability",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="carrierdocument",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="carrierdocument",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vérifié par",
            ),
        ),
        migrations.AddField(
            model_name="carriernotification",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="carrierreview",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="carrierreview",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carrier_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auteur",
            ),
        ),
        migrations.AddField(
            model_name="carrierroute",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carrier_routes",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddIndex(
            model_name="carrier",
            index=models.Index(
                fields=["status", "carrier_type"], name="carriers_ca_status_7f3ecc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carrier",
            index=models.Index(
                fields=["is_available", "status"], name="carriers_ca_is_avai_37936d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carrier",
            index=models.Index(
                fields=["user", "status"], name="carriers_ca_user_id_484ac0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carrieravailability",
            index=models.Index(
                fields=["carrier", "start_datetime", "is_booked"],
                name="carriers_ca_carrier_9528db_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carriernotification",
            index=models.Index(
                fields=["carrier", "is_read", "created_at"],
                name="carriers_ca_carrier_83a765_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carrierreview",
            index=models.Index(
                fields=["carrier", "is_approved", "is_visible"],
                name="carriers_ca_carrier_ece7b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carrierreview",
            index=models.Index(
                fields=["reviewer", "created_at"], name="carriers_ca_reviewe_0792c4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="carrierreview",
            unique_together={("carrier", "reviewer")},
        ),
        migrations.AddIndex(
            model_name="carrierroute",
            index=models.Index(
                fields=["start_country", "end_country"],
                name="carriers_ca_start_c_24d42f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carrierroute",
            index=models.Index(
                fields=["departure_date", "is_active"],
                name="carriers_ca_departu_d158ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carrierroute",
            index=models.Index(
                fields=["carrier", "is_active"], name="carriers_ca_carrier_c67da6_idx"
            ),
        ),
    ]
