# Generated by Django 6.0 on 2026-01-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carriers", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrier",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approuvé le"
            ),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CASH", "Espèces"),
                    ("BANK_TRANSFER", "Virement bancaire"),
                    ("CARD", "Carte bancaire"),
                    ("MOBILE_MONEY", "Mobile money"),
                    ("PAYPAL", "PayPal"),
                    ("STRIPE", "Stripe"),
                    ("OTHER", "Autre"),
                ],
                max_length=20,
                verbose_name="Méthode de paiement",
            ),
        ),
    ]
