# Generated by Django 6.0 on 2026-01-10 14:02

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carriers", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarrierOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre de l'offre"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("IMMEDIATE", "Immédiate"),
                            ("SCHEDULED", "Planifiée"),
                            ("RECURRING", "Récurrente"),
                            ("GROUPED", "Groupée"),
                        ],
                        default="IMMEDIATE",
                        max_length=20,
                        verbose_name="Type d'offre",
                    ),
                ),
                (
                    "start_country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Pays de départ"
                    ),
                ),
                (
                    "start_city",
                    models.CharField(max_length=100, verbose_name="Ville de départ"),
                ),
                (
                    "end_country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Pays d'arrivée"
                    ),
                ),
                (
                    "end_city",
                    models.CharField(max_length=100, verbose_name="Ville d'arrivée"),
                ),
                (
                    "available_from",
                    models.DateTimeField(verbose_name="Disponible à partir du"),
                ),
                (
                    "available_until",
                    models.DateTimeField(verbose_name="Disponible jusqu'au"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "€"),
                            ("USD", "$"),
                            ("GBP", "£"),
                            ("MAD", "DH"),
                            ("XOF", "CFA"),
                        ],
                        default="EUR",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "available_weight",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=8,
                        verbose_name="Poids disponible (kg)",
                    ),
                ),
                (
                    "available_volume",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="Volume disponible (m³)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_booked",
                    models.BooleanField(default=False, verbose_name="Réservée"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de vues"
                    ),
                ),
                (
                    "inquiries_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de demandes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Offre de transporteur",
                "verbose_name_plural": "Offres de transporteurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarrierSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nom de la recherche"
                    ),
                ),
                (
                    "search_criteria",
                    models.JSONField(
                        default=dict, verbose_name="Critères de recherche"
                    ),
                ),
                (
                    "alerts_enabled",
                    models.BooleanField(default=False, verbose_name="Alertes activées"),
                ),
                (
                    "alert_frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Quotidien"),
                            ("WEEKLY", "Hebdomadaire"),
                            ("IMMEDIATE", "Immédiat"),
                        ],
                        default="DAILY",
                        max_length=20,
                        verbose_name="Fréquence des alertes",
                    ),
                ),
                (
                    "last_alert_sent",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière alerte envoyée"
                    ),
                ),
                (
                    "last_results_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de résultats précédent"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Recherche de transporteur",
                "verbose_name_plural": "Recherches de transporteurs",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CarrierStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_success_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Taux de livraison réussie (%)",
                    ),
                ),
                (
                    "on_time_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Taux de ponctualité (%)",
                    ),
                ),
                (
                    "satisfaction_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Taux de satisfaction (%)",
                    ),
                ),
                (
                    "zone_rankings",
                    models.JSONField(
                        default=dict,
                        help_text="Format: {'zone': 'rank', ...}",
                        verbose_name="Classements par zone",
                    ),
                ),
                (
                    "monthly_stats",
                    models.JSONField(
                        default=dict,
                        help_text="Format: {'YYYY-MM': {'missions': X, 'revenue': Y}, ...}",
                        verbose_name="Statistiques mensuelles",
                    ),
                ),
                (
                    "total_distance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Distance totale parcourue (km)",
                    ),
                ),
                (
                    "total_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Heures totales de travail",
                    ),
                ),
                (
                    "avg_delivery_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Temps moyen de livraison"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Statistique de transporteur",
                "verbose_name_plural": "Statistiques de transporteurs",
            },
        ),
        migrations.CreateModel(
            name="CollectionDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date de collecte")),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                ("end_time", models.TimeField(verbose_name="Heure de fin")),
                (
                    "is_scheduled",
                    models.BooleanField(default=False, verbose_name="Planifié"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Terminé"),
                ),
                (
                    "planned_total_weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=8,
                        verbose_name="Poids total planifié (kg)",
                    ),
                ),
                (
                    "planned_total_volume",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="Volume total planifié (m³)",
                    ),
                ),
                (
                    "actual_total_weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=8,
                        verbose_name="Poids total réel (kg)",
                    ),
                ),
                (
                    "actual_total_volume",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="Volume total réel (m³)",
                    ),
                ),
                (
                    "collection_route",
                    models.JSONField(
                        default=list,
                        help_text="Liste ordonnée des adresses à collecter",
                        verbose_name="Itinéraire de collecte",
                    ),
                ),
                (
                    "optimized_route",
                    models.JSONField(
                        default=list,
                        help_text="Itinéraire optimisé pour la collecte",
                        verbose_name="Itinéraire optimisé",
                    ),
                ),
                (
                    "estimated_distance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Distance estimée (km)",
                    ),
                ),
                (
                    "estimated_duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Durée estimée"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Jour de collecte",
                "verbose_name_plural": "Jours de collecte",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Début de période")),
                ("period_end", models.DateField(verbose_name="Fin de période")),
                (
                    "total_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Total des dépenses",
                    ),
                ),
                (
                    "total_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Total des revenus",
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Bénéfice net",
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="carriers/expense_reports/%Y/%m/%d/",
                        verbose_name="Fichier rapport",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Approuvé"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approuvé le"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rapport de dépenses",
                "verbose_name_plural": "Rapports de dépenses",
                "ordering": ["-period_end"],
            },
        ),
        migrations.CreateModel(
            name="FinancialTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("PAYMENT", "Paiement"),
                            ("EXPENSE", "Dépense"),
                            ("REFUND", "Remboursement"),
                            ("COMMISSION", "Commission"),
                            ("BONUS", "Bonus"),
                        ],
                        max_length=20,
                        verbose_name="Type de transaction",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "€"),
                            ("USD", "$"),
                            ("GBP", "£"),
                            ("MAD", "DH"),
                            ("XOF", "CFA"),
                        ],
                        default="EUR",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CASH", "Espèces"),
                            ("BANK_TRANSFER", "Virement bancaire"),
                            ("CARD", "Carte bancaire"),
                            ("MOBILE_MONEY", "Mobile money"),
                            ("PAYPAY", "PayPal"),
                            ("STRIPE", "Stripe"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Méthode de paiement",
                    ),
                ),
                (
                    "is_prepaid",
                    models.BooleanField(default=False, verbose_name="Prépaiement"),
                ),
                (
                    "expense_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FUEL", "Carburant"),
                            ("TOLL", "Péages"),
                            ("MAINTENANCE", "Entretien"),
                            ("INSURANCE", "Assurance"),
                            ("PARKING", "Parking"),
                            ("MEALS", "Repas"),
                            ("ACCOMMODATION", "Hébergement"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie de dépense",
                    ),
                ),
                (
                    "expense_description",
                    models.TextField(
                        blank=True, verbose_name="Description de la dépense"
                    ),
                ),
                (
                    "expense_receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="carriers/expenses/%Y/%m/%d/",
                        verbose_name="Reçu de dépense",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro de reçu"
                    ),
                ),
                (
                    "receipt_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="carriers/receipts/%Y/%m/%d/",
                        verbose_name="Fichier reçu",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro de facture"
                    ),
                ),
                (
                    "invoice_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="carriers/invoices/%Y/%m/%d/",
                        verbose_name="Fichier facture",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de transaction",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=True, verbose_name="Terminé"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Transaction financière",
                "verbose_name_plural": "Transactions financières",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mission_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Numéro de mission"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("ACCEPTED", "Acceptée"),
                            ("COLLECTING", "En collecte"),
                            ("IN_TRANSIT", "En transit"),
                            ("DELIVERING", "En livraison"),
                            ("DELIVERED", "Livrée"),
                            ("CANCELLED", "Annulée"),
                            ("PROBLEM", "Problème"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Basse"),
                            ("MEDIUM", "Moyenne"),
                            ("HIGH", "Haute"),
                            ("URGENT", "Urgente"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "sender_address",
                    models.TextField(verbose_name="Adresse de l'expéditeur"),
                ),
                (
                    "sender_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Téléphone expéditeur"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        max_length=200, verbose_name="Nom du destinataire"
                    ),
                ),
                (
                    "recipient_address",
                    models.TextField(verbose_name="Adresse du destinataire"),
                ),
                (
                    "recipient_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        region=None,
                        verbose_name="Téléphone destinataire",
                    ),
                ),
                (
                    "merchandise_type",
                    models.CharField(max_length=50, verbose_name="Type de marchandise"),
                ),
                (
                    "custom_merchandise_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Type personnalisé"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=3, max_digits=8, verbose_name="Poids (kg)"
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Longueur (m)"
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Largeur (m)"
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Hauteur (m)"
                    ),
                ),
                (
                    "preferred_pickup_date",
                    models.DateField(verbose_name="Date de collecte préférée"),
                ),
                (
                    "preferred_delivery_date",
                    models.DateField(verbose_name="Date de livraison préférée"),
                ),
                (
                    "actual_pickup_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de collecte réelle"
                    ),
                ),
                (
                    "actual_delivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de livraison réelle"
                    ),
                ),
                (
                    "agreed_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix convenu (€)"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "€"),
                            ("USD", "$"),
                            ("GBP", "£"),
                            ("MAD", "DH"),
                            ("XOF", "CFA"),
                        ],
                        default="EUR",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "delivery_proof_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="missions/delivery_proofs/%Y/%m/%d/",
                        verbose_name="Photo preuve de livraison",
                    ),
                ),
                (
                    "recipient_signature",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="missions/signatures/%Y/%m/%d/",
                        verbose_name="Signature du destinataire",
                    ),
                ),
                (
                    "delivery_notes",
                    models.TextField(blank=True, verbose_name="Notes de livraison"),
                ),
                (
                    "has_incident",
                    models.BooleanField(default=False, verbose_name="A un incident"),
                ),
                (
                    "incident_description",
                    models.TextField(
                        blank=True, verbose_name="Description de l'incident"
                    ),
                ),
                (
                    "incident_resolved",
                    models.BooleanField(default=False, verbose_name="Incident résolu"),
                ),
                (
                    "delay_reason",
                    models.TextField(blank=True, verbose_name="Raison du retard"),
                ),
                (
                    "delay_duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Durée du retard"
                    ),
                ),
                (
                    "collection_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordre dans lequel collecter cet objet",
                        verbose_name="Ordre de collecte",
                    ),
                ),
                (
                    "position_in_vehicle",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Arrière gauche, dessus, etc.",
                        max_length=100,
                        verbose_name="Position dans le véhicule",
                    ),
                ),
                (
                    "is_fragile",
                    models.BooleanField(default=False, verbose_name="Fragile"),
                ),
                (
                    "requires_special_handling",
                    models.BooleanField(
                        default=False,
                        verbose_name="Nécessite une manipulation spéciale",
                    ),
                ),
                (
                    "current_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="Localisation actuelle",
                    ),
                ),
                (
                    "last_location_update",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Dernière mise à jour de localisation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Mission",
                "verbose_name_plural": "Missions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="carrier",
            name="accepted_merchandise_types",
            field=models.JSONField(
                default=list,
                help_text="Liste des types de marchandises acceptées",
                verbose_name="Types de marchandises acceptées",
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="coverage_cities",
            field=models.TextField(
                blank=True,
                help_text="Ex: Paris, Lyon, Marseille",
                verbose_name="Villes de couverture (séparées par des virgules)",
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="coverage_countries",
            field=django_countries.fields.CountryField(
                blank=True,
                max_length=746,
                multiple=True,
                verbose_name="Pays de couverture",
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="custom_merchandise_types",
            field=models.TextField(
                blank=True,
                help_text="Saisissez vos types personnalisés séparés par des virgules",
                verbose_name="Types de marchandises personnalisés",
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="id_back",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="carriers/ids/%Y/%m/%d/",
                verbose_name="Verso pièce d'identité",
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="id_front",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="carriers/ids/%Y/%m/%d/",
                verbose_name="Recto pièce d'identité",
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="kyc_verified",
            field=models.BooleanField(default=False, verbose_name="KYC vérifié"),
        ),
        migrations.AddField(
            model_name="carrier",
            name="kyc_verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="KYC vérifié le"
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="carriers/profile_photos/%Y/%m/%d/",
                verbose_name="Photo de profil",
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="rgpd_consent",
            field=models.BooleanField(default=False, verbose_name="Consentement RGPD"),
        ),
        migrations.AddField(
            model_name="carrier",
            name="terms_accepted",
            field=models.BooleanField(
                default=False, verbose_name="Conditions générales acceptées"
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="two_factor_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Authentification à 2 facteurs activée"
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="vehicle_photo_back",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="carriers/vehicles/%Y/%m/%d/",
                verbose_name="Photo arrière du véhicule",
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="vehicle_photo_front",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="carriers/vehicles/%Y/%m/%d/",
                verbose_name="Photo avant du véhicule",
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="vehicle_photo_side",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="carriers/vehicles/%Y/%m/%d/",
                verbose_name="Photo côté du véhicule",
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="weekly_schedule",
            field=models.JSONField(
                default=dict,
                help_text="Format: {'monday': {'start': '08:00', 'end': '18:00'}, ...}",
                verbose_name="Emploi du temps hebdomadaire",
            ),
        ),
        migrations.AddField(
            model_name="carrierdocument",
            name="customs_country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, verbose_name="Pays concerné"
            ),
        ),
        migrations.AddField(
            model_name="carrierdocument",
            name="customs_type",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Type de document douanier"
            ),
        ),
        migrations.AddField(
            model_name="carrierdocument",
            name="declaration_data",
            field=models.JSONField(
                default=dict,
                help_text="Données pour le générateur de formulaires",
                verbose_name="Données de déclaration",
            ),
        ),
        migrations.AddField(
            model_name="carrierdocument",
            name="is_customs_document",
            field=models.BooleanField(default=False, verbose_name="Document douanier"),
        ),
        migrations.AddField(
            model_name="carrierdocument",
            name="reminder_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de rappel"
            ),
        ),
        migrations.AddField(
            model_name="carrierdocument",
            name="reminder_sent",
            field=models.BooleanField(default=False, verbose_name="Rappel envoyé"),
        ),
        migrations.AddField(
            model_name="carriernotification",
            name="alert_level",
            field=models.CharField(
                choices=[
                    ("INFO", "Information"),
                    ("WARNING", "Avertissement"),
                    ("URGENT", "Urgent"),
                ],
                default="INFO",
                max_length=20,
                verbose_name="Niveau d'alerte",
            ),
        ),
        migrations.AddField(
            model_name="carrierreview",
            name="careful",
            field=models.BooleanField(default=False, verbose_name="Soigneux"),
        ),
        migrations.AddField(
            model_name="carrierreview",
            name="carrier_response",
            field=models.TextField(blank=True, verbose_name="Réponse du transporteur"),
        ),
        migrations.AddField(
            model_name="carrierreview",
            name="good_communication",
            field=models.BooleanField(default=False, verbose_name="Bon communicateur"),
        ),
        migrations.AddField(
            model_name="carrierreview",
            name="on_time",
            field=models.BooleanField(default=False, verbose_name="À l'heure"),
        ),
        migrations.AddField(
            model_name="carrierreview",
            name="recommended",
            field=models.BooleanField(default=False, verbose_name="Recommandé"),
        ),
        migrations.AddField(
            model_name="carrierreview",
            name="response_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de réponse"
            ),
        ),
        migrations.AddField(
            model_name="carrierroute",
            name="estimated_transit_time",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Temps de transit estimé"
            ),
        ),
        migrations.AddField(
            model_name="carrierroute",
            name="fuel_costs",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="Coûts de carburant (€)",
            ),
        ),
        migrations.AddField(
            model_name="carrierroute",
            name="tax_costs",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="Coûts de taxes (€)",
            ),
        ),
        migrations.AddField(
            model_name="carrierroute",
            name="toll_costs",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="Coûts de péages (€)",
            ),
        ),
        migrations.AlterField(
            model_name="carrierdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("ID_CARD", "Carte d'identité"),
                    ("PASSPORT", "Passeport"),
                    ("DRIVER_LICENSE", "Permis de conduire"),
                    ("VEHICLE_REGISTRATION", "Carte grise"),
                    ("INSURANCE", "Assurance"),
                    ("COMPANY_REGISTRATION", "Immatriculation société"),
                    ("TAX_CERTIFICATE", "Certificat fiscal"),
                    ("CUSTOMS_DOCUMENT", "Document douanier"),
                    ("OTHER", "Autre"),
                ],
                max_length=30,
                verbose_name="Type de document",
            ),
        ),
        migrations.AlterField(
            model_name="carriernotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("NEW_MISSION", "Nouvelle mission"),
                    ("MISSION_UPDATE", "Mise à jour de mission"),
                    ("PAYMENT_RECEIVED", "Paiement reçu"),
                    ("REVIEW_RECEIVED", "Avis reçu"),
                    ("DOCUMENT_VERIFIED", "Document vérifié"),
                    ("STATUS_CHANGED", "Statut changé"),
                    ("SYSTEM", "Système"),
                    ("COLLECTION_DAY", "Jour de collecte"),
                    ("EXPENSE_ALERT", "Alerte dépense"),
                    ("DOCUMENT_EXPIRY", "Document expiré"),
                    ("ROUTE_OPTIMIZED", "Itinéraire optimisé"),
                    ("NEW_OFFER", "Nouvelle offre"),
                ],
                max_length=30,
                verbose_name="Type de notification",
            ),
        ),
        migrations.AddIndex(
            model_name="carrier",
            index=models.Index(
                fields=["coverage_countries"], name="carriers_ca_coverag_7869e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carriernotification",
            index=models.Index(
                fields=["notification_type", "created_at"],
                name="carriers_ca_notific_706257_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carrierreview",
            index=models.Index(
                fields=["rating", "created_at"], name="carriers_ca_rating_201e05_idx"
            ),
        ),
        migrations.AddField(
            model_name="carrieroffer",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="carriersearch",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carrier_searches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="carrierstatistics",
            name="carrier",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statistics",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="collectionday",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_days",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="expensereport",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approuvé par",
            ),
        ),
        migrations.AddField(
            model_name="expensereport",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_reports",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="financialtransaction",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carrier_missions",
                to="carriers.carrier",
                verbose_name="Transporteur",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_missions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Expéditeur",
            ),
        ),
        migrations.AddField(
            model_name="financialtransaction",
            name="mission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="carriers.mission",
                verbose_name="Mission",
            ),
        ),
        migrations.AddIndex(
            model_name="carrieroffer",
            index=models.Index(
                fields=["carrier", "is_active", "available_from"],
                name="carriers_ca_carrier_058c2f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carrieroffer",
            index=models.Index(
                fields=["start_country", "end_country", "is_active"],
                name="carriers_ca_start_c_f9f288_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carrieroffer",
            index=models.Index(
                fields=["offer_type", "is_active"],
                name="carriers_ca_offer_t_d2a038_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carriersearch",
            index=models.Index(
                fields=["user", "alerts_enabled"], name="carriers_ca_user_id_6827de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collectionday",
            index=models.Index(
                fields=["carrier", "date", "is_completed"],
                name="carriers_co_carrier_2e7774_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collectionday",
            unique_together={("carrier", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="expensereport",
            unique_together={("carrier", "period_start", "period_end")},
        ),
        migrations.AddIndex(
            model_name="mission",
            index=models.Index(
                fields=["mission_number"], name="carriers_mi_mission_2516e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mission",
            index=models.Index(
                fields=["carrier", "status"], name="carriers_mi_carrier_feed52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mission",
            index=models.Index(
                fields=["sender", "status"], name="carriers_mi_sender__374693_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mission",
            index=models.Index(
                fields=["status", "preferred_pickup_date"],
                name="carriers_mi_status_5d53ce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mission",
            index=models.Index(
                fields=["collection_order"], name="carriers_mi_collect_c72a33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialtransaction",
            index=models.Index(
                fields=["carrier", "transaction_type", "transaction_date"],
                name="carriers_fi_carrier_d6db84_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialtransaction",
            index=models.Index(
                fields=["mission", "transaction_type"],
                name="carriers_fi_mission_28a778_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialtransaction",
            index=models.Index(
                fields=["transaction_date", "is_completed"],
                name="carriers_fi_transac_5678e3_idx",
            ),
        ),
    ]
