# Generated by Django 6.0 on 2026-01-11 19:16

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carriers", "0003_carrieroffer_carriersearch_carrierstatistics_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carrier",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_verify_carrier", "Peut vérifier les transporteurs"),
                    ("can_approve_carrier", "Peut approuver les transporteurs"),
                    (
                        "can_view_carrier_stats",
                        "Peut voir les statistiques des transporteurs",
                    ),
                ],
                "verbose_name": "Profil Transporteur",
                "verbose_name_plural": "Profils Transporteurs",
            },
        ),
        migrations.RemoveIndex(
            model_name="carrier",
            name="carriers_ca_is_avai_37936d_idx",
        ),
        migrations.AddField(
            model_name="carrier",
            name="completed_transport_missions",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Missions de transport complétées"
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="total_transport_missions",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Total des missions de transport"
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="transport_available_from",
            field=models.DateField(
                blank=True, null=True, verbose_name="Disponible à partir du (transport)"
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="transport_available_until",
            field=models.DateField(
                blank=True, null=True, verbose_name="Disponible jusqu'au (transport)"
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="transport_average_rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Note moyenne transport",
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="transport_company_address",
            field=models.TextField(
                blank=True,
                help_text="Adresse spécifique pour l'activité de transport",
                verbose_name="Adresse de l'entreprise de transport",
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="transport_company_name",
            field=models.CharField(
                blank=True,
                help_text="Spécifique à l'activité de transport",
                max_length=200,
                verbose_name="Nom de l'entreprise de transport",
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="transport_company_registration",
            field=models.CharField(
                blank=True,
                help_text="Spécifique à l'activité de transport",
                max_length=100,
                verbose_name="Numéro d'immatriculation transport",
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="transport_insurance_certificate",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="carriers/documents/transport_insurance/",
                verbose_name="Certificat d'assurance transport",
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="transport_is_available",
            field=models.BooleanField(
                default=True, verbose_name="Disponible pour des missions de transport"
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="transport_operator_license",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="carriers/documents/transport_license/",
                verbose_name="Licence d'exploitation transport",
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="transport_success_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=100.0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Taux de réussite transport (%)",
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="transport_tax_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Numéro fiscal transport"
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="transport_total_reviews",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Nombre total d'avis transport"
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="transport_weekly_schedule",
            field=models.JSONField(
                default=dict,
                help_text="Disponibilités spécifiques pour le transport",
                verbose_name="Emploi du temps hebdomadaire transport",
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="vehicle_registration_certificate",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="carriers/documents/vehicle_registration/",
                verbose_name="Certificat d'immatriculation véhicule",
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="accepted_merchandise_types",
            field=models.JSONField(
                default=list,
                help_text="Liste des types de marchandises acceptées pour le transport",
                verbose_name="Types de marchandises acceptées",
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="carrier_type",
            field=models.CharField(
                choices=[
                    ("CARRIER", "Transporteur Professionnel"),
                    ("CARRIER_PERSONAL", "Transporteur Particulier"),
                ],
                help_text="Note: doit correspondre au rôle dans le profil utilisateur",
                max_length=20,
                verbose_name="Type de transporteur",
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="coverage_cities",
            field=models.TextField(
                blank=True,
                help_text="Villes spécifiques pour le transport, séparées par des virgules",
                verbose_name="Villes de couverture (transport)",
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="coverage_countries",
            field=django_countries.fields.CountryField(
                blank=True,
                max_length=746,
                multiple=True,
                verbose_name="Pays de couverture transport",
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="currency",
            field=models.CharField(
                choices=[
                    ("EUR", "€"),
                    ("USD", "$"),
                    ("GBP", "£"),
                    ("MAD", "DH"),
                    ("XOF", "CFA"),
                ],
                default="EUR",
                max_length=3,
                verbose_name="Devise pour le transport",
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="id_back",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="carriers/ids/%Y/%m/%d/",
                verbose_name="Verso pièce d'identité (transport)",
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="id_front",
            field=models.ImageField(
                blank=True,
                help_text="Pour vérification spécifique transport",
                null=True,
                upload_to="carriers/ids/%Y/%m/%d/",
                verbose_name="Recto pièce d'identité (transport)",
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo spécifique pour le profil transporteur",
                null=True,
                upload_to="carriers/profile_photos/%Y/%m/%d/",
                verbose_name="Photo de profil transporteur",
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="provides_insurance",
            field=models.BooleanField(
                default=False, verbose_name="Fournit l'assurance transport"
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="rejection_reason",
            field=models.TextField(
                blank=True, verbose_name="Raison du rejet (transport)"
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("APPROVED", "Approuvé"),
                    ("REJECTED", "Rejeté"),
                    ("SUSPENDED", "Suspendu"),
                    ("INACTIVE", "Inactif"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Statut de transporteur",
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="user",
            field=models.OneToOneField(
                help_text="L'utilisateur auquel est associé ce profil transporteur",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carrier_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="verification_level",
            field=models.IntegerField(
                default=0,
                help_text="De 0 (non vérifié) à 5 (entièrement vérifié) - spécifique au transport",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Niveau de vérification transporteur",
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Vérifié le (transport)"
            ),
        ),
        migrations.AddIndex(
            model_name="carrier",
            index=models.Index(
                fields=["transport_is_available", "status"],
                name="carriers_ca_transpo_dec1af_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="available_from",
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="available_until",
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="average_rating",
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="company_address",
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="company_registration",
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="completed_missions",
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="insurance_certificate",
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="is_available",
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="kyc_verified",
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="kyc_verified_at",
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="operator_license",
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="registration_certificate",
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="rgpd_consent",
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="success_rate",
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="tax_id",
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="terms_accepted",
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="total_missions",
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="total_reviews",
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="two_factor_enabled",
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="weekly_schedule",
        ),
    ]
