# Generated by Django 6.0 on 2026-01-15 08:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.CharField(max_length=255)),
                ("source_language", models.CharField(max_length=10)),
                ("field_name", models.CharField(max_length=100)),
                ("original_text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                            ("partial", "Partiel"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("target_languages", models.JSONField(default=list)),
                ("completed_languages", models.JSONField(default=list)),
                ("failed_languages", models.JSONField(default=list)),
                ("total_characters", models.PositiveIntegerField(default=0)),
                ("api_calls_count", models.PositiveIntegerField(default=0)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("error_details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Travail de traduction",
                "verbose_name_plural": "Travaux de traduction",
                "db_table": "translation_jobs",
            },
        ),
        migrations.CreateModel(
            name="TranslationMemory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_text_hash", models.CharField(db_index=True, max_length=64)),
                ("source_language", models.CharField(max_length=10)),
                ("target_language", models.CharField(max_length=10)),
                ("translated_text", models.TextField()),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mémoire de traduction",
                "verbose_name_plural": "Mémoires de traduction",
                "db_table": "translation_memory",
            },
        ),
        migrations.CreateModel(
            name="TranslationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_translate_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Traduction automatique activée"
                    ),
                ),
                (
                    "preferred_languages",
                    models.JSONField(
                        default=list,
                        help_text="Liste des codes de langue par ordre de préférence",
                        verbose_name="Langues préférées",
                    ),
                ),
                (
                    "show_translation_badge",
                    models.BooleanField(
                        default=True,
                        verbose_name="Afficher le badge 'Traduit automatiquement'",
                    ),
                ),
                (
                    "allow_translation_editing",
                    models.BooleanField(
                        default=True, verbose_name="Autoriser l'édition des traductions"
                    ),
                ),
                (
                    "quality_threshold",
                    models.FloatField(
                        default=0.7,
                        help_text="Score de confiance minimum pour accepter une traduction automatique",
                        verbose_name="Seuil de qualité minimum",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paramètre de traduction",
                "verbose_name_plural": "Paramètres de traduction",
                "db_table": "translation_settings",
            },
        ),
        migrations.CreateModel(
            name="APILog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("endpoint", models.CharField(max_length=255)),
                ("source_language", models.CharField(max_length=10)),
                ("target_language", models.CharField(max_length=10)),
                ("character_count", models.PositiveIntegerField()),
                ("success", models.BooleanField()),
                ("response_time", models.FloatField()),
                ("status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "cost_estimate",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Log API",
                "verbose_name_plural": "Logs API",
                "db_table": "translation_api_logs",
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="translation_created_b6c492_idx"
                    ),
                    models.Index(
                        fields=["success"], name="translation_success_79e8c6_idx"
                    ),
                    models.Index(
                        fields=["source_language", "target_language"],
                        name="translation_source__9871e9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.CharField(max_length=255)),
                ("field_name", models.CharField(max_length=100)),
                ("language", models.CharField(max_length=10)),
                ("translated_text", models.TextField()),
                ("source_text", models.TextField()),
                ("source_language", models.CharField(max_length=10)),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("auto", "Automatique"),
                            ("human", "Humaine"),
                            ("edited", "Éditée"),
                            ("reviewed", "Révisée"),
                        ],
                        default="auto",
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_current", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Traduction",
                "verbose_name_plural": "Traductions",
                "db_table": "translations",
            },
        ),
    ]
