# Generated by Django 6.0 on 2026-01-15 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("translations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_translations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="translation",
            name="last_edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="edited_translations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="translationjob",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="translation",
            name="translation_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="translations",
                to="translations.translationjob",
            ),
        ),
        migrations.AddIndex(
            model_name="translationmemory",
            index=models.Index(
                fields=["source_text_hash"], name="translation_source__4e1ee6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="translationmemory",
            index=models.Index(
                fields=["source_language", "target_language"],
                name="translation_source__1529d6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="translationmemory",
            unique_together={
                ("source_text_hash", "source_language", "target_language")
            },
        ),
        migrations.AddField(
            model_name="translationsettings",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddIndex(
            model_name="translationjob",
            index=models.Index(
                fields=["status", "created_at"], name="translation_status_61a53b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="translationjob",
            index=models.Index(
                fields=["content_type", "object_id", "field_name"],
                name="translation_content_37925a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="translationjob",
            index=models.Index(
                fields=["created_at"], name="translation_created_076622_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="translation",
            index=models.Index(
                fields=[
                    "content_type",
                    "object_id",
                    "field_name",
                    "language",
                    "is_current",
                ],
                name="translation_content_c3d30a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="translation",
            index=models.Index(
                fields=["language", "is_current"], name="translation_languag_24eb18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="translation",
            index=models.Index(
                fields=["created_at"], name="translation_created_035e0e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="translation",
            unique_together={
                ("content_type", "object_id", "field_name", "language", "version")
            },
        ),
    ]
