"""
Django settings for ebi3 project.
Generated by 'django-admin startproject' using Django 4.2.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-^i3vk0pvad&06t9-a(+(^#fmmsl_a=qh+8wfe=q_)#ab9n0o*%"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['saidi19.pythonanywhere.com', 'localhost', '127.0.0.1']

# Application definition
INSTALLED_APPS = [
    # Django core apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'django.contrib.sites',

    # Vos applications
    'users.apps.UsersConfig',
    'ads.apps.AdsConfig',
    'carriers.apps.CarriersConfig',
    'colis.apps.ColisConfig',
    'payments.apps.PaymentsConfig',
    'core.apps.CoreConfig',
    'dashboard.apps.DashboardConfig',
    'logistics.apps.LogisticsConfig',
    'messaging.apps.MessagingConfig',
    'reviews.apps.ReviewsConfig',
    'tracking.apps.TrackingConfig',
    'translations.apps.TranslationsConfig',  # Ajouté une seule fois

    # Nouvelle application d'audit
    'audit.apps.AuditConfig',

    # Packages tiers
    'crispy_forms',
    'crispy_bootstrap5',
    'phonenumber_field',
    'django_countries',
    'rosetta',
    'mptt',
    'django_cleanup.apps.CleanupConfig',
]

MIDDLEWARE = [
    'ebi3.middlewares.minimal.MinimalMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'ebi3.middlewares.two_factor.TwoFactorAuthMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = "ebi3.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'core/templates'),
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'core.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = "ebi3.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

if 'spatialite' not in DATABASES['default']['ENGINE']:
    DATABASES['default']['ENGINE'] = 'django.contrib.gis.db.backends.spatialite'

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LANGUAGES = [
    ('ar', 'العربية'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('de', 'Deutsch'),
    ('it', 'Italiano'),
    ('es', 'Español'),
    ('pt', 'Português'),
    ('pl', 'Polski'),
]

LANGUAGE_CODE = 'fr'

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

AUTH_USER_MODEL = 'users.User'
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'core:home'
LOGOUT_REDIRECT_URL = 'core:home'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Configuration Celery
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Paris'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    },
    'translations': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'translation-cache',
    }
}

SITE_ID = 1

# ============================================================================
# CONFIGURATION DEEPSEEK TRANSLATION
# ============================================================================

# Configuration de base DeepSeek
DEEPSEEK_API_KEY = os.environ.get('DEEPSEEK_API_KEY', '')
DEEPSEEK_CONFIG = {
    'API_KEY': DEEPSEEK_API_KEY,
    'ENABLED_LANGUAGES': ['fr', 'en', 'ar', 'es', 'de', 'it', 'pt', 'ru', 'zh', 'tr', 'nl'],
    'AUTO_TRANSLATE_FIELDS': ['title', 'description', 'content', 'body', 'message', 'comment'],
    'BATCH_SIZE': 5,
    'RETRY_ATTEMPTS': 3,
    'QUALITY_THRESHOLD': 0.7,
    'RATE_LIMIT_PER_MINUTE': 60,
    'API_URL': 'https://api.deepseek.com/v1/chat/completions',
    'MODEL': 'deepseek-chat',
    'TIMEOUT': 30,
    'TEMPERATURE': 0.1,
    'MAX_TOKENS': 4000,
}

# Middleware pour la traduction
MIDDLEWARE += [
    'translations.middleware.LanguageDetectionMiddleware',
    'translations.middleware.TranslationPreferencesMiddleware',
]

# Ajouter les langues DeepSeek à LANGUAGES si elles n'existent pas déjà
DEEPSEEK_LANGUAGES = [
    ('fr', 'Français'),
    ('en', 'English'),
    ('ar', 'العربية'),
    ('es', 'Español'),
    ('de', 'Deutsch'),
    ('it', 'Italiano'),
    ('pt', 'Português'),
    ('ru', 'Русский'),
    ('zh', '中文'),
    ('tr', 'Türkçe'),
    ('nl', 'Nederlands'),
]

for lang in DEEPSEEK_LANGUAGES:
    if lang not in LANGUAGES:
        LANGUAGES.append(lang)

# Configuration Celery pour les traductions
try:
    from celery.schedules import crontab
    TRANSLATION_CELERY_BEAT_SCHEDULE = {
        'cleanup-old-translation-jobs': {
            'task': 'translations.tasks.cleanup_old_jobs',
            'schedule': crontab(hour=3, minute=0),
            'args': (30,),
        },
        'retry-failed-translation-jobs': {
            'task': 'translations.tasks.retry_failed_jobs',
            'schedule': crontab(hour='*/2', minute=30),
        },
        'update-translation-cache': {
            'task': 'translations.tasks.update_translation_cache',
            'schedule': crontab(hour=4, minute=0),
        },
    }

    # Fusionner avec le schedule existant
    if 'CELERY_BEAT_SCHEDULE' not in locals():
        CELERY_BEAT_SCHEDULE = {}

    CELERY_BEAT_SCHEDULE.update(TRANSLATION_CELERY_BEAT_SCHEDULE)

except ImportError:
    print("Celery non disponible pour les tâches de traduction")

# Paramètres de sécurité pour les traductions
TRANSLATION_SECURITY = {
    'DATA_RETENTION_DAYS': 365,
    'MAX_TEXT_LENGTH': 10000,
    'DAILY_LIMIT_PER_USER': 100,
}