"""
Django settings for ebi3 project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-^i3vk0pvad&06t9-a(+(^#fmmsl_a=qh+8wfe=q_)#ab9n0o*%"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['saidi19.pythonanywhere.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    # Django core apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',  # Pour GeoDjango
    'django.contrib.sites',

    # Vos applications
    'users.apps.UsersConfig',
    'ads.apps.AdsConfig',
    'carriers.apps.CarriersConfig',
    'colis.apps.ColisConfig',
    'payments.apps.PaymentsConfig',
    'core.apps.CoreConfig',
    'dashboard.apps.DashboardConfig',
    'logistics.apps.LogisticsConfig',
    'messaging.apps.MessagingConfig',
    'reviews.apps.ReviewsConfig',
    'tracking.apps.TrackingConfig',

    # Nouvelle application d'audit
    'audit.apps.AuditConfig',

    # Packages tiers
    'crispy_forms',
    'crispy_bootstrap5',
    'phonenumber_field',
    'django_countries',
    'rosetta',  # Pour les traductions
    'mptt',
    'django_cleanup.apps.CleanupConfig',
]

# ============================================================================
# MIDDLEWARES DE SÉCURITÉ
# ============================================================================

MIDDLEWARE = [
    # 'ebi3.middlewares.fix_security.FixedSecurityMiddleware',  # DISABLED for now  # FIX for Django 6.0
    # ========== SÉCURITÉ ==========
    # 1. Sécurité des cookies (Doit être en haut)
    'ebi3.middlewares.minimal.MinimalMiddleware',
    'django.middleware.security.SecurityMiddleware',

    # 2. Protection contre les attaques Clickjacking
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # ========== WHITENOISE (SERVIR LES FICHIERS STATICS) ==========
    # 3. Gestion des fichiers statiques en production
    'whitenoise.middleware.WhiteNoiseMiddleware',

    # ========== SESSION ET AUTHENTIFICATION ==========
    # 4. Gestion des sessions
    'django.contrib.sessions.middleware.SessionMiddleware',

    # 5. Internationalisation (Doit être après SessionMiddleware)
    'django.middleware.locale.LocaleMiddleware',

    # ========== SÉCURITÉ SUPPLÉMENTAIRE ==========
    # 6. Middleware personnalisé pour détection d'attaques
    # 'ebi3.middlewares.custom_security.SecurityMiddleware',  # DISABLED for now

    # 7. Middleware personnalisé pour audit et logging
    # 'ebi3.middlewares.audit.AuditMiddleware',  # DISABLED for now

    # 8. Protection CSRF (Doit être après SessionMiddleware)
    'django.middleware.csrf.CsrfViewMiddleware',

    # 9. Authentification
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # 10. Middleware personnalisé pour la vérification 2FA
    'ebi3.middlewares.two_factor.TwoFactorAuthMiddleware',

    # 11. Middleware personnalisé pour la limitation de débit
    # 'ebi3.middlewares.rate_limit.RateLimitMiddleware',  # DISABLED for now

    # ========== MESSAGES ET SESSION ==========
    # 12. Messages flash
    'django.contrib.messages.middleware.MessageMiddleware',

    # ========== COMMUN ==========
    # 13. Middleware commun (Doit être en dernier parmi les Django standards)
    'django.middleware.common.CommonMiddleware',
]

# ============================================================================
# CONFIGURATION DE SÉCURITÉ
# ============================================================================

# Configuration pour django.middleware.security.SecurityMiddleware
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'  # Empêche le framing (protection clickjacking)
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# ========== HTTPS ET SSL ==========
# En production, forcer HTTPS
# Note: Pour le développement, laissez à False
SECURE_SSL_REDIRECT = False  # Mettre à True en production avec HTTPS
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# ========== COOKIES SÉCURISÉS ==========
# Pour le développement, laisser à False
# En production avec HTTPS, mettre à True
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'  # ou 'Strict' pour plus de sécurité
CSRF_COOKIE_SAMESITE = 'Lax'

# ========== HEADERS DE SÉCURITÉ ==========
# Décommenter en production derrière un proxy
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ========== LIMITATION DE DÉBIT ==========
# Configuration pour RateLimitMiddleware
RATE_LIMIT_ENABLED = True
RATE_LIMIT_DEFAULT = '1000/hour'  # Limite par défaut
RATE_LIMIT_ANONYMOUS = '100/hour'  # Limite pour utilisateurs anonymes
RATE_LIMIT_AUTHENTICATED = '5000/hour'  # Limite pour utilisateurs authentifiés

# Routes spécifiques avec limites différentes
RATE_LIMIT_SPECIAL = {
    '/api/v1/': '1000/hour',  # API
    '/admin/': '50/hour',  # Admin
    '/payments/': '100/hour',  # Paiements
    '/users/login/': '10/hour',  # Login
    '/users/register/': '5/hour',  # Inscription
    '/payments/checkout/': '30/hour',  # Checkout
}

# ========== DÉTECTION D'ATTAQUES ==========
SECURITY_MIDDLEWARE_CONFIG = {
    'block_suspicious_ips': True,
    'max_login_attempts': 5,
    'login_block_time': 3600,  # 1 heure
    'detect_sql_injection': True,
    'detect_xss': True,
    'detect_bruteforce': True,
    'log_all_requests': True,
}

# ========== CONFIGURATION AUDIT ==========
AUDIT_MIDDLEWARE_CONFIG = {
    'log_requests': True,
    'log_responses': True,
    'log_errors': True,
    'log_slow_requests': True,
    'slow_request_threshold': 5.0,  # secondes
    'log_sensitive_data': False,
    'mask_fields': ['password', 'token', 'secret', 'key', 'pin'],
}

# ========== 2FA CONFIGURATION ==========
TWO_FACTOR_MIDDLEWARE_CONFIG = {
    'enabled': True,
    'required_for_staff': True,
    'required_for_sensitive_actions': True,
    'sensitive_paths': [
        '/admin/',
        '/payments/',
        '/wallet/',
        '/settings/',
        '/api/v1/',
    ],
    'remember_device_days': 30,
}

ROOT_URLCONF = "ebi3.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'core/templates'),
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',  # Pour les traductions
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'core.context_processors.site_settings',  # Nous allons créer ceci
            ],
        },
    },
]


WSGI_APPLICATION = "ebi3.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

if 'spatialite' not in DATABASES['default']['ENGINE']:
    DATABASES['default']['ENGINE'] = 'django.contrib.gis.db.backends.spatialite'


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]




# Configuration des langues pour le multilinguisme
LANGUAGES = [
    ('ar', 'العربية'),     # Arabe
    ('fr', 'Français'),    # Français
    ('en', 'English'),     # Anglais
    ('de', 'Deutsch'),     # Allemand
    ('it', 'Italiano'),    # Italien
    ('es', 'Español'),     # Espagnol
    ('pt', 'Português'),   # Portugais
    ('pl', 'Polski'),      # Polonais
]

LANGUAGE_CODE = 'fr'  # Langue par défaut

# Configuration pour l'arabe (RTL)
PARLER_LANGUAGES = {
    None: (
        {'code': 'ar', 'name': 'العربية', 'rtl': True},
        {'code': 'fr', 'name': 'Français'},
        {'code': 'en', 'name': 'English'},
        {'code': 'de', 'name': 'Deutsch'},
        {'code': 'it', 'name': 'Italiano'},
        {'code': 'es', 'name': 'Español'},
        {'code': 'pt', 'name': 'Português'},
        {'code': 'pl', 'name': 'Polski'},
    ),
    'default': {
        'fallback': 'fr',
        'hide_untranslated': False,
    }
}

# Configuration des chemins
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Configuration des timezones
# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Configuration de l'authentification
AUTH_USER_MODEL = 'users.User'
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'core:home'
LOGOUT_REDIRECT_URL = 'core:home'

# Configuration Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"



# Configuration des fichiers statiques et médias
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Configuration WhiteNoise pour les fichiers statiques
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuration des fichiers upload
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# Pour les images
DJANGORESIZED_DEFAULT_SIZE = [1200, 800]
DJANGORESIZED_DEFAULT_QUALITY = 85
DJANGORESIZED_DEFAULT_KEEP_META = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Configuration de Rosetta
ROSETTA_SHOW_AT_ADMIN_PANEL = True
ROSETTA_ENABLE_TRANSLATION_SUGGESTIONS = True
ROSETTA_WSGI_AUTO_RELOAD = True

LANGUAGE_COOKIE_NAME = 'ebi3_language'
LANGUAGE_COOKIE_AGE = 31536000  # 1 an en secondes
LANGUAGE_COOKIE_PATH = '/'
LANGUAGE_COOKIE_SECURE = False  # Mettre à True en production
LANGUAGE_COOKIE_HTTPONLY = True
LANGUAGE_COOKIE_SAMESITE = 'Lax'

# Configuration Celery
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Paris'
CELERY_BEAT_SCHEDULE = {
    'update-package-statuses-daily': {
        'task': 'colis.tasks.daily_maintenance_workflow',
        'schedule': 86400.0,  # 24 heures
    },
    'weekly-reports': {
        'task': 'colis.tasks.weekly_report_workflow',
        'schedule': 604800.0,  # 7 jours
    },
    'hourly-offer-processing': {
        'task': 'colis.tasks.process_expired_offers',
        'schedule': 3600.0,  # 1 heure
    },
}


# Configuration SEO
SEO_CONFIG = {
    'SITEMAP_URL': '/colis/sitemap.xml',
    'ROBOTS_URL': '/colis/robots.txt',
    'CANONICAL_BASE': 'https://ebi3.com',
    'DEFAULT_META_DESCRIPTION': 'Transportez vos colis en toute sécurité avec Ebi3',
    'DEFAULT_META_KEYWORDS': 'colis, transport, expatriés, livraison',
    'OG_IMAGE': '/static/img/og-image.jpg',
    'TWITTER_SITE': '@ebi3_app',
}

# Google Search Console verification
GOOGLE_SITE_VERIFICATION = 'your-verification-code'

# Bing Webmaster Tools verification
BING_SITE_VERIFICATION = 'your-bing-verification-code'

# Configuration du cache pour les middlewares de sécurité
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Configuration des logs
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'security': {
            'format': '{asctime} - {levelname} - SECURITY - {message}',
            'style': '{',
        },
        'audit': {
            'format': '{asctime} - {levelname} - AUDIT - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'security_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/security.log'),
            'maxBytes': 1024*1024*10,  # 10MB
            'backupCount': 5,
            'formatter': 'security',
        },
        'audit_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/audit.log'),
            'maxBytes': 1024*1024*10,  # 10MB
            'backupCount': 5,
            'formatter': 'audit',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['security_file', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'ebi3.middlewares.security': {
            'handlers': ['security_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'ebi3.middlewares.audit': {
            'handlers': ['audit_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Créer le dossier logs s'il n'existe pas
if not os.path.exists(os.path.join(BASE_DIR, 'logs')):
    os.makedirs(os.path.join(BASE_DIR, 'logs'))

SITE_ID = 1